/**
 * Map file names / extensions → highlight.js language ids.
 * Superset by design: CodePreview bundles only common grammars and falls
 * back to plain text for the rest, while codeEditorLang (CodeMirror) covers
 * nearly all of these ids in the editor.
 */

const EXT_LANG: Record<string, string> = {
  // JS / TS
  ts: "typescript",
  tsx: "typescript",
  mts: "typescript",
  cts: "typescript",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  // Data / docs
  json: "json",
  jsonc: "json",
  json5: "json",
  md: "markdown",
  mdx: "markdown",
  // Systems
  rs: "rust",
  go: "go",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hh: "cpp",
  hxx: "cpp",
  cs: "csharp",
  // JVM / mobile
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  scala: "scala",
  sc: "scala",
  groovy: "groovy",
  gradle: "groovy",
  swift: "swift",
  m: "objectivec",
  mm: "objectivec",
  // Scripting
  py: "python",
  pyw: "python",
  pyi: "python",
  rb: "ruby",
  php: "php",
  pl: "perl",
  pm: "perl",
  lua: "lua",
  r: "r",
  jl: "julia",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hrl: "erlang",
  hs: "haskell",
  lhs: "haskell",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  elm: "elm",
  ml: "ocaml",
  mli: "ocaml",
  fs: "fsharp",
  fsi: "fsharp",
  fsx: "fsharp",
  coffee: "coffeescript",
  litcoffee: "coffeescript",
  // Shell / Windows
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "bash",
  command: "bash",
  ps1: "powershell",
  psm1: "powershell",
  psd1: "powershell",
  bat: "dos",
  cmd: "dos",
  // Config / markup
  yml: "yaml",
  yaml: "yaml",
  toml: "ini",
  ini: "ini",
  conf: "ini",
  cfg: "ini",
  properties: "properties",
  prop: "properties",
  env: "bash",
  // Styles
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "less",
  // Web templates (hljs has no dedicated vue/svelte — xml is closest)
  html: "xml",
  htm: "xml",
  xml: "xml",
  svg: "xml",
  vue: "xml",
  svelte: "xml",
  astro: "xml",
  // Build / infra
  dockerfile: "dockerfile",
  containerfile: "dockerfile",
  makefile: "makefile",
  mk: "makefile",
  cmake: "cmake",
  nginx: "nginx",
  tf: "plaintext", // no HCL grammar in core hljs
  hcl: "plaintext",
  nix: "nix",
  // Data / API
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  proto: "protobuf",
  http: "http",
  rest: "http",
  // Diff / patch
  diff: "diff",
  patch: "diff",
  // Graphics / shaders
  glsl: "glsl",
  frag: "glsl",
  vert: "glsl",
  wgsl: "plaintext",
  // Misc common
  wasm: "wasm",
  wat: "wasm",
  vim: "vim",
  vimrc: "vim",
  tex: "latex",
  latex: "latex",
  ltx: "latex",
  matlab: "matlab",
  f: "fortran",
  f90: "fortran",
  f95: "fortran",
  for: "fortran",
  vb: "vbnet",
  vbs: "vbnet",
  lisp: "lisp",
  cl: "lisp",
  el: "lisp",
  scm: "scheme",
  ss: "scheme",
  rkt: "scheme",
  tcl: "tcl",
  awk: "awk",
  nims: "nim",
  nim: "nim",
  cr: "crystal",
  ino: "arduino",
  pde: "arduino",
  ahk: "autohotkey",
  zig: "plaintext",
  txt: "plaintext",
  log: "plaintext",
  csv: "plaintext",
  tsv: "plaintext",
};

/** Special whole-filename mappings (case-insensitive). */
const NAME_LANG: Record<string, string> = {
  dockerfile: "dockerfile",
  containerfile: "dockerfile",
  makefile: "makefile",
  gnumakefile: "makefile",
  gemfile: "ruby",
  rakefile: "ruby",
  podfile: "ruby",
  brewfile: "ruby",
  "cargo.toml": "ini",
  "cargo.lock": "ini",
  "pyproject.toml": "ini",
  "package.json": "json",
  "package-lock.json": "json",
  "tsconfig.json": "json",
  "jsconfig.json": "json",
  "composer.json": "json",
  "go.mod": "plaintext",
  "go.sum": "plaintext",
  cmakelists: "cmake",
  "cmakelists.txt": "cmake",
  ".gitignore": "plaintext",
  ".gitattributes": "plaintext",
  ".dockerignore": "plaintext",
  ".npmrc": "ini",
  ".editorconfig": "ini",
  ".env": "bash",
  ".env.local": "bash",
  ".env.example": "bash",
  ".env.development": "bash",
  ".env.production": "bash",
  ".bashrc": "bash",
  ".zshrc": "bash",
  ".profile": "bash",
  ".bash_profile": "bash",
  nginx: "nginx",
  "nginx.conf": "nginx",
  "vite.config.ts": "typescript",
  "vite.config.js": "javascript",
  "webpack.config.js": "javascript",
  "rollup.config.js": "javascript",
  "next.config.js": "javascript",
  "next.config.mjs": "javascript",
  "tailwind.config.js": "javascript",
  "tailwind.config.ts": "typescript",
  "jest.config.js": "javascript",
  "jest.config.ts": "typescript",
  "vitest.config.ts": "typescript",
  "vitest.config.js": "javascript",
  "eslint.config.js": "javascript",
  "eslint.config.mjs": "javascript",
  "prettier.config.js": "javascript",
};

export function languageFromFileName(name: string): string {
  const base = name.replace(/\\/g, "/").split("/").pop() || name;
  const lower = base.toLowerCase();
  if (NAME_LANG[lower]) return NAME_LANG[lower];
  // Compound extensions (e.g. component.tsx already handled via last ext)
  const ext = lower.includes(".") ? lower.split(".").pop() || "" : "";
  if (ext && EXT_LANG[ext]) return EXT_LANG[ext];
  return "plaintext";
}
