import type { SettingsEntry } from "../types";

/** Settings catalog entries — about section. */
export const ABOUT_ENTRIES: readonly SettingsEntry[] = [
  // ── about ──
  {
    id: "about.app",
    section: "about",
    anchorId: "settings-anchor-about",
    labelKey: "settings.aboutApp",
    keywords: ["about", "version", "update", "关于", "關於", "版本", "更新"],
  },
  {
    id: "about.cli",
    section: "about",
    anchorId: "settings-anchor-aboutCli",
    labelKey: "settings.cliUpdate",
    descKeys: [
      "settings.cliUpdateDesc",
      "settings.cliChannel.switchHint",
      "settings.cliChannel.pinLabel",
    ],
    keywords: [
      "cli",
      "grok update",
      "channel",
      "alpha",
      "stable",
      "cli version",
      "CLI 版本",
      "更新通道",
      "更新頻道",
      "更新",
    ],
  },
  {
    id: "about.tutorial",
    section: "about",
    anchorId: "settings-anchor-tutorial",
    labelKey: "tutorial.replay",
    descKeys: ["tutorial.replayDesc", "tutorial.menu"],
    keywords: [
      "tutorial",
      "product tour",
      "onboarding",
      "walkthrough",
      "help",
      "guide",
      "教程",
      "教學",
      "新手引导",
      "新手引導",
      "产品导览",
      "產品導覽",
      "帮助",
      "幫助",
    ],
  },
  {
    id: "about.whatsNew",
    section: "about",
    anchorId: "settings-anchor-whatsNew",
    labelKey: "whatsNew.replay",
    descKeys: ["whatsNew.replayDesc", "whatsNew.menu"],
    keywords: [
      "what's new",
      "whats new",
      "changelog",
      "release notes",
      "update notes",
      "announcement",
      "更新公告",
      "更新说明",
    ],
  },
  {
    id: "about.developerMode",
    section: "about",
    anchorId: "settings-anchor-developerMode",
    labelKey: "settings.developerMode",
    descKeys: ["settings.developerModeDesc"],
    keywords: [
      "developer",
      "dev mode",
      "debug",
      "simulate update",
      "开发模式",
      "开发者",
    ],
  },
  {
    id: "about.updateSim",
    section: "about",
    anchorId: "settings-anchor-updateSim",
    labelKey: "settings.updateSim",
    descKeys: ["settings.updateSimDesc"],
    keywords: [
      "simulate update",
      "fake update",
      "update badge",
      "sidebar update",
      "模拟更新",
    ],
  },
];
