import type { SettingsEntry } from "../types";

/** Search catalog entries for wallpaper sources and the X route selector. */
export const APPEARANCE_WALLPAPER_ENTRIES: readonly SettingsEntry[] = [
  {
    id: "appearance.wallpaper",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-wallpaper",
    labelKey: "settings.wallpaper",
    descKeys: [
      "settings.wallpaperDesc",
      "settings.wallpaperScrim",
      "settings.wallpaperScrimDesc",
      "settings.wallpaperBlur",
      "settings.wallpaperBlurDesc",
      "settings.wallpaperBlurMacHint",
      "settings.wallpaperFromX",
      "settings.wallpaperWeb",
      "settings.wallpaperOpenverse",
      "settings.wallpaperPexels",
      "settings.wallpaperSource.pexels.keyRequired",
      "settings.wallpaperImagine",
      "settings.wallpaperGrokAlbum",
    ],
    keywords: [
      "wallpaper",
      "background",
      "scrim",
      "opacity",
      "blur",
      "overlay",
      "x",
      "twitter",
      "web image search",
      "openverse",
      "pexels",
      "pexels api key",
      "imagine",
      "grok album",
      "grok saved",
      "imagine saved",
      "背景",
      "壁纸",
      "壁紙",
      "网络图片",
      "網路圖片",
      "图片搜索",
      "圖片搜尋",
      "相册",
      "相簿",
      "收藏",
      "遮罩",
      "模糊",
      "透明度",
    ],
  },
  {
    id: "appearance.wallpaperXSearchMode",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-wallpaper-x-search-mode",
    labelKey: "settings.wallpaperXSearchMode",
    descKeys: [
      "settings.wallpaperXSearchModeDesc",
      "settings.wallpaperXSearchMode.cli",
      "settings.wallpaperXSearchMode.responsesPreview",
    ],
    keywords: [
      "x search route",
      "responses api",
      "grok build cli",
      "preview",
      "twitter wallpaper",
      "X 搜索渠道",
      "X 搜尋管道",
      "壁纸搜索模式",
      "壁紙搜尋模式",
    ],
  },
];
