import type { SettingsEntry } from "../types";

/** Settings catalog entries — appearance section. */
export const APPEARANCE_ENTRIES: readonly SettingsEntry[] = [
  // ── appearance · theme ──
  {
    id: "appearance.theme",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-theme",
    labelKey: "settings.theme",
    descKeys: [
      "settings.themeDesc",
      "settings.themeSystem",
      "settings.themeLight",
      "settings.themeDark",
    ],
    keywords: ["theme", "dark", "light", "system", "auto", "跟随系统"],
  },
  {
    id: "appearance.themeSchedule",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-themeSchedule",
    labelKey: "settings.themeSchedule",
    descKeys: [
      "settings.themeScheduleDesc",
      "settings.themeScheduleLightFrom",
      "settings.themeScheduleDarkFrom",
      "settings.themeSchedule.nextSwitch",
      "settings.themeSchedule.nextSwitchTomorrow",
      "settings.themeSchedule.invalidEqual",
      "settings.themeSchedule.invalidTimes",
      "settings.themeSchedule.inactivePref",
    ],
    keywords: [
      "schedule",
      "timed",
      "auto theme",
      "light from",
      "dark from",
      "next switch",
      "clock",
      "定时",
      "定時",
      "按时切换",
      "按時切換",
      "浅色开始",
      "深色开始",
      "下次切换",
      "下次切換",
    ],
  },
  {
    id: "appearance.skin",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin",
    labelKey: "settings.skin",
    descKeys: ["settings.skinDesc"],
    keywords: [
      "skin",
      "color pack",
      "accent",
      "皮肤",
      "皮膚",
      "外观包",
      "外觀包",
      "主题包",
      "主題包",
    ],
  },
  {
    id: "appearance.wallpaper",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-wallpaper",
    labelKey: "settings.wallpaper",
    descKeys: [
      "settings.wallpaperDesc",
      "settings.wallpaperScrim",
      "settings.wallpaperScrimDesc",
      "settings.wallpaperBlur",
      "settings.wallpaperBlurDesc",
      "settings.wallpaperBlurMacHint",
      "settings.wallpaperFromX",
      "settings.wallpaperXSearchMode",
      "settings.wallpaperXSearchModeDesc",
      "settings.wallpaperXSearchMode.responsesPreview",
      "settings.wallpaperImagine",
      "settings.wallpaperWeb",
      "settings.wallpaperSource.web.placeholder",
      "settings.wallpaperOpenverse",
      "settings.wallpaperPexels",
      "settings.wallpaperSource.pexels.keyRequired",
      "settings.wallpaperGrokAlbum",
      "settings.wallpaperColor",
      "settings.wallpaperColorDesc",
    ],
    keywords: [
      "wallpaper",
      "solid color",
      "color",
      "绿豆沙",
      "纯色",
      "莫兰迪",
      "莫蘭迪",
      "护眼",
      "護眼",
      "web image search",
      "network image search",
      "openverse",
      "pexels",
      "api key",
      "background",
      "scrim",
      "opacity",
      "blur",
      "overlay",
      "x",
      "twitter",
      "imagine",
      "grok album",
      "grok saved",
      "imagine saved",
      "背景",
      "壁纸",
      "网络找图",
      "网页图片",
      "相册",
      "相簿",
      "收藏",
      "遮罩",
      "模糊",
      "透明度",
    ],
  },
  {
    id: "appearance.composerOpacity",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-composerOpacity",
    labelKey: "settings.composerOpacity",
    descKeys: ["settings.composerOpacityDesc", "settings.surfaceOpacity"],
    keywords: [
      "composer",
      "input",
      "opacity",
      "transparency",
      "输入框",
      "輸入框",
      "透明度",
    ],
  },
  {
    id: "appearance.uiOpacity",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-uiOpacity",
    labelKey: "settings.uiOpacity",
    descKeys: ["settings.uiOpacityDesc", "settings.surfaceOpacity"],
    keywords: [
      "card",
      "code block",
      "bubble",
      "opacity",
      "transparency",
      "file card",
      "status pill",
      "avatar",
      "卡片",
      "代码块",
      "代碼塊",
      "透明度",
      "头像",
      "頭像",
      "状态",
      "狀態",
    ],
  },
  {
    id: "appearance.settingsOpacity",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-settingsOpacity",
    labelKey: "settings.settingsOpacity",
    descKeys: ["settings.settingsOpacityDesc", "settings.surfaceOpacity"],
    keywords: [
      "settings page",
      "settings overlay",
      "opacity",
      "transparency",
      "floor",
      "设置页",
      "設定頁",
      "设置页面",
      "設定頁面",
      "透明度",
      "不透明",
    ],
  },
  {
    id: "appearance.textColor",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-textColor",
    labelKey: "settings.textColor",
    descKeys: [
      "settings.textColorDesc",
      "settings.textColorFollowTheme",
      "settings.appearanceReset",
    ],
    keywords: [
      "text color",
      "font color",
      "ink",
      "foreground",
      "文字颜色",
      "文字顏色",
      "字体颜色",
      "字體顏色",
    ],
  },
  {
    id: "appearance.fontShadow",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-fontShadow",
    labelKey: "settings.fontShadow",
    descKeys: ["settings.fontShadowDesc"],
    keywords: [
      "text shadow",
      "font shadow",
      "drop shadow",
      "字体阴影",
      "字體陰影",
      "文字阴影",
      "文字陰影",
    ],
  },
  {
    id: "appearance.chromeReset",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-appearanceReset",
    labelKey: "settings.appearanceReset",
    descKeys: [
      "settings.appearanceResetTitle",
      "settings.appearanceResetBody",
    ],
    keywords: [
      "restore defaults",
      "factory",
      "reset appearance",
      "恢复默认",
      "恢復預設",
      "出厂",
      "出廠",
    ],
  },
  {
    id: "appearance.skinPresets",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin-presets",
    labelKey: "settings.skinPresets.title",
    descKeys: ["settings.skinPresets.desc"],
    keywords: [
      "preset",
      "skin pack",
      "grokskin",
      "export",
      "import",
      "外观预设",
      "外觀預設",
      "皮肤包",
    ],
  },
  {
    id: "appearance.skinCatalog",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin-catalog",
    labelKey: "settings.skinCatalog.browse",
    descKeys: ["settings.skinCatalog.desc"],
    keywords: [
      "catalog",
      "theme store",
      "download",
      "仓库",
      "倉庫",
      "主题",
    ],
  },
];
