import type { SettingsEntry } from "../types";

/** Settings catalog entries — general / app section. */
export const GENERAL_APP_ENTRIES: readonly SettingsEntry[] = [
  // ── general / app ──
  {
    id: "general.language",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-language",
    labelKey: "settings.language",
    descKeys: ["settings.languageDesc", "settings.section.general"],
    keywords: [
      "language",
      "locale",
      "中文",
      "english",
      "system",
      "跟随系统",
      "跟隨系統",
    ],
  },
  {
    id: "general.sessionDataMode",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sessionDataMode",
    labelKey: "settings.sessionDataMode",
    descKeys: [
      "settings.sessionDataModeDesc",
      "settings.modeShared",
      "settings.modeIndependent",
      "settings.sessionModeHelp",
      "settings.sessionDataMode.status",
      "settings.sessionDataMode.banner.sharedWithCli",
      "settings.sessionDataMode.banner.noRewriteSecrets",
      "settings.sessionDataMode.banner.conflictPossible",
      "settings.sessionDataMode.risk.noSilentMerge",
      "settings.sessionDataMode.customRequiresIndependent",
      "settings.cliSessions",
    ],
    keywords: [
      "session data",
      "shared",
      "independent",
      "cli sessions",
      "agent-home",
      "GROK_HOME",
      "~/.grok",
      "merge",
      "recycle",
      "no silent merge",
      "会话数据",
      "共享",
      "独立",
    ],
  },
  {
    id: "general.cliSessions",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-cliSessions",
    labelKey: "settings.cliSessions",
    descKeys: [
      "settings.cliSessionsDesc",
      "settings.cliSessionsManage",
      "settings.cliSessionsIndependentNote",
      "settings.cliSessionsImportOpen",
      "settings.cliSessionsDelete",
      "settings.cliSessionsDeleteUnlinked",
      "settings.cliSessionsFilterPlaceholder",
      "settings.cliSessionsSearchViaCli",
      "settings.cliSessionsEmptyCliMissing",
      "settings.cliSessions.clearFilters",
      "settings.cliSessions.filterLinked",
      "settings.cliSessions.filterUnlinked",
      "settings.cliSessions.err.cli_missing",
    ],
    keywords: [
      "cli sessions",
      "import session",
      "manage sessions",
      "agent session id",
      "resume",
      "delete session",
      "search sessions",
      "first prompt",
      "linked",
      "unlinked",
      "clear filters",
      "cli missing",
      "CLI 会话",
      "管理会话",
      "导入会话",
      "删除会话",
      "搜索会话",
      "首条提示",
      "已关联",
      "未关联",
      "清除筛选",
    ],
  },
  {
    id: "general.voiceHotkeyEnabled",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceHotkeyEnabled",
    labelKey: "settings.voiceHotkeyEnabled",
    descKeys: ["settings.voiceHotkeyEnabledDesc", "settings.section.voice"],
    keywords: [
      "voice",
      "hotkey",
      "shortcut",
      "live voice",
      "keyboard",
      "语音",
      "快捷键",
      "实时语音",
    ],
  },
  {
    id: "general.voiceId",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceId",
    labelKey: "settings.voiceId",
    descKeys: ["settings.voiceIdDesc", "settings.section.voice"],
    keywords: ["voice", "speaker", "tts", "语音", "音色"],
  },
  {
    id: "general.voiceDictationAutoSend",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceDictationAutoSend",
    labelKey: "settings.voiceDictationAutoSend",
    descKeys: ["settings.voiceDictationAutoSendDesc"],
    keywords: ["dictation", "auto send", "听写", "语音输入"],
  },
  {
    id: "general.voiceKeepAgentsOnEnd",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceKeepAgentsOnEnd",
    labelKey: "settings.voiceKeepAgentsOnEnd",
    descKeys: ["settings.voiceKeepAgentsOnEndDesc"],
    keywords: ["voice", "keep agents", "语音", "保留"],
  },
  {
    id: "general.sttEngine",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sttEngine",
    labelKey: "settings.sttEngine",
    descKeys: [
      "settings.sttEngineDesc",
      "settings.section.voice",
    ],
    keywords: [
      "dictation",
      "stt",
      "speech to text",
      "transcription",
      "openai compatible",
      "custom endpoint",
      "base url",
      "provider template",
      "preset",
      "local",
      "faster-whisper",
      "groq",
      "whisper",
      "mistral",
      "voxtral",
      "简体",
      "繁体",
      "繁体中文",
      "simplified",
      "traditional",
      "听写",
      "语音转文字",
      "语音输入",
      "自定义端点",
      "提供方",
      "模板",
    ],
  },
  {
    id: "general.keychain",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keychain",
    labelKey: "settings.storeApiKeysInKeychain",
    descKeys: ["settings.storeApiKeysInKeychainDesc"],
    keywords: [
      "keychain",
      "api key",
      "secrets",
      "钥匙串",
      "鑰匙串",
      "密钥串",
      "密鑰串",
      "密钥",
      "密鑰",
      "保险箱",
      "保險箱",
    ],
  },
  {
    id: "general.clearMemory",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-clearMemory",
    labelKey: "settings.clearWorkspaceMemory",
    descKeys: ["settings.clearWorkspaceMemoryDesc"],
    keywords: [
      "clear memory",
      "workspace memory",
      "清除记忆",
      "清除記憶",
      "清空记忆",
      "清空記憶",
      "工作区记忆",
      "工作區記憶",
    ],
  },
  {
    id: "general.reopenLastSession",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-reopenLastSession",
    labelKey: "settings.reopenLastSession",
    descKeys: ["settings.reopenLastSessionDesc"],
    keywords: [
      "reopen",
      "restore session",
      "恢复上次会话",
      "恢復上次會話",
      "重新打开",
      "重新打開",
      "恢复会话",
      "恢復會話",
    ],
  },
  {
    id: "general.closeToTray",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-closeToTray",
    labelKey: "settings.closeToTray",
    descKeys: ["settings.closeToTrayDesc"],
    keywords: ["tray", "close", "minimize", "托盘", "系統匣", "关闭"],
  },
  {
    id: "general.keepTrayForSchedules",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keepTrayForSchedules",
    labelKey: "settings.keepTrayForSchedules",
    descKeys: ["settings.keepTrayForSchedulesDesc"],
    keywords: [
      "tray",
      "schedules",
      "automations",
      "background",
      "keep",
      "scheduled",
      "托盘",
      "已安排",
      "调度",
      "系统匣",
      "排程",
    ],
  },
  {
    id: "general.trayBusyBadge",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-trayBusyBadge",
    labelKey: "settings.trayBusyBadge",
    descKeys: [
      "settings.trayBusyBadgeDesc",
      "settings.trayBusyBadge.status.off",
      "settings.trayBusyBadge.status.idle",
      "settings.trayBusyBadge.status.busy",
      "settings.trayBusyBadge.status.capped",
    ],
    keywords: [
      "badge",
      "dock",
      "tray",
      "busy",
      "unread",
      "count",
      "角标",
      "徽章",
      "托盘",
      "忙碌",
      "未读",
      "未讀",
      "系統匣",
      "notify",
      "notification",
    ],
  },
  {
    id: "general.winTaskbarOverlay",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-winTaskbarOverlay",
    labelKey: "settings.winTaskbarOverlay",
    descKeys: ["settings.winTaskbarOverlayDesc"],
    keywords: [
      "windows",
      "taskbar",
      "overlay",
      "badge",
      "unread",
      "count",
      "任务栏",
      "工作列",
      "角标",
      "未读",
      "未讀",
    ],
  },
  {
    id: "general.notifyHonesty",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyHonesty",
    labelKey: "settings.notify.honesty.title",
    descKeys: [
      "settings.notify.honesty.desc",
      "settings.notify.honesty.ok",
      "settings.notify.honesty.osDenied",
      "settings.notify.honesty.osDefault",
      "settings.notify.honesty.osUnsupported",
      "settings.notify.honesty.prefsOff",
      "settings.notify.honesty.quietHours",
    ],
    keywords: [
      "notification",
      "desktop",
      "permission",
      "os",
      "quiet hours",
      "dnd",
      "notify",
      "桌面通知",
      "系统权限",
      "免打扰",
      "通知權限",
    ],
  },
  {
    id: "general.launchAtLogin",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-launchAtLogin",
    labelKey: "settings.launchAtLogin",
    descKeys: ["settings.launchAtLoginDesc"],
    keywords: [
      "launch",
      "login",
      "startup",
      "autostart",
      "boot",
      "automation",
      "scheduled",
      "schedule",
      "daemon",
      "background",
      "开机",
      "登录",
      "啟動",
      "登入",
      "自动化",
      "已安排",
      "排程",
      "后台",
      "背景",
    ],
  },
  {
    id: "general.windowAlwaysOnTop",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-windowAlwaysOnTop",
    labelKey: "settings.windowAlwaysOnTop",
    descKeys: ["settings.windowAlwaysOnTopDesc"],
    keywords: [
      "always on top",
      "pin",
      "float",
      "stay on top",
      "置顶",
      "置頂",
      "窗口",
      "視窗",
    ],
  },
  {
    id: "general.notifyOnTurnDone",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnTurnDone",
    labelKey: "settings.notifyOnTurnDone",
    descKeys: ["settings.notifyOnTurnDoneDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "turn done",
      "notify",
      "桌面通知",
      "完成通知",
    ],
  },
  {
    id: "general.notifyOnPermission",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnPermission",
    labelKey: "settings.notifyOnPermission",
    descKeys: ["settings.notifyOnPermissionDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "permission",
      "notify",
      "桌面通知",
      "授权通知",
    ],
  },
  {
    id: "general.notifySound",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifySound",
    labelKey: "settings.notifySound",
    descKeys: ["settings.notifySoundDesc"],
    keywords: [
      "notification",
      "sound",
      "beep",
      "audio",
      "alert",
      "notify",
      "通知声音",
      "提示音",
    ],
  },
  {
    id: "general.notifyQuietHours",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyQuietHours",
    labelKey: "settings.notifyQuietHours",
    descKeys: [
      "settings.notifyQuietHoursDesc",
      "settings.notifyQuietHoursStart",
      "settings.notifyQuietHoursEnd",
      "settings.notifyQuietHours.activeNow",
    ],
    keywords: [
      "quiet hours",
      "do not disturb",
      "dnd",
      "notification",
      "desktop",
      "mute",
      "night",
      "免打扰",
      "勿扰",
      "静音时段",
      "桌面通知",
    ],
  },
  {
    id: "general.stopAllSkipConfirm",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-stopAllSkipConfirm",
    labelKey: "settings.stopAllSkipConfirm",
    descKeys: ["settings.stopAllSkipConfirmDesc"],
    keywords: [
      "stop all",
      "skip confirm",
      "busy sessions",
      "tasks",
      "dashboard",
      "no confirm",
      "全部停止",
      "跳过确认",
      "忙碌会话",
    ],
  },
  {
    id: "general.alwaysQuitWithoutAsking",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-alwaysQuitWithoutAsking",
    labelKey: "settings.alwaysQuitWithoutAsking",
    descKeys: ["settings.alwaysQuitWithoutAskingDesc"],
    keywords: [
      "quit",
      "exit",
      "close",
      "busy",
      "confirm",
      "always quit",
      "without asking",
      "退出",
      "结束",
      "忙碌",
      "确认",
      "不再询问",
    ],
  },
  {
    id: "general.openTarget",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-openTarget",
    labelKey: "settings.openTarget",
    descKeys: [
      "settings.openTargetDesc",
      "settings.openFinder",
      "settings.openTargetEmpty",
      "settings.openTargetPreferredMissing",
      "settings.openTargetUnavailable",
    ],
    keywords: [
      "open in",
      "finder",
      "editor",
      "no editors",
      "preferred editor",
      "打开方式",
      "打開方式",
      "外部编辑器",
      "外部編輯器",
      "首选编辑器",
      "首選編輯器",
    ],
  },
];
