import type { SettingsEntry } from "../types";

/** Settings catalog entries — general section. */
export const GENERAL_ENTRIES: readonly SettingsEntry[] = [
  // ── general / composer ──
  {
    id: "general.prefsScope",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-prefsScope",
    labelKey: "settings.prefsScope",
    descKeys: [
      "settings.prefsScopeDesc",
      "settings.prefsScope.global",
      "settings.prefsScope.project",
      "settings.prefsScope.session",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "prefs",
      "scope",
      "偏好",
      "偏好設定",
      "作用域",
      "预设范围",
      "预设範圍",
    ],
  },
  {
    id: "general.availableModels",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-availableModels",
    labelKey: "settings.availableModels",
    descKeys: ["settings.availableModelsDesc"],
    keywords: ["models", "model list", "模型", "模型列表", "模型清單", "可用模型"],
  },
  {
    id: "general.composerMinRows",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerMinRows",
    labelKey: "settings.composerMinRows",
    descKeys: [
      "settings.composerMinRowsDesc",
      "settings.composerMinRows.2",
      "settings.composerMinRows.3",
      "settings.composerMinRows.5",
      "settings.composerMinRows.8",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "height",
      "min height",
      "minimum height",
      "rows",
      "input size",
      "textarea",
      "输入框高度",
      "輸入框高度",
      "最小高度",
      "行数",
      "行數",
    ],
  },
  {
    id: "general.composerSendKey",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSendKey",
    labelKey: "settings.composerSendKey",
    descKeys: [
      "settings.composerSendKeyDesc",
      "settings.composerSendKey.enter",
      "settings.composerSendKey.modEnter",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "send",
      "enter",
      "mod-enter",
      "quote",
      "comment",
      "cmd enter",
      "ctrl enter",
      "newline",
      "keyboard",
      "发送",
      "發送",
      "发送键",
      "發送鍵",
      "回车发送",
      "回車發送",
      "换行",
      "換行",
      "快捷键",
      "快捷鍵",
    ],
  },
  {
    id: "general.composerSpellcheck",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSpellcheck",
    labelKey: "settings.composerSpellcheck",
    descKeys: [
      "settings.composerSpellcheckDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "spellcheck",
      "spell check",
      "spelling",
      "typo",
      "autocorrect",
      "拼写检查",
      "拼寫檢查",
      "拼写",
      "拼寫",
      "拼写校正",
      "拼寫校正",
    ],
  },
  {
    id: "general.composerDraftStats",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerDraftStats",
    labelKey: "settings.composerDraftStats",
    descKeys: [
      "settings.composerDraftStatsDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "draft",
      "stats",
      "character",
      "char count",
      "word count",
      "words",
      "length",
      "草稿统计",
      "草稿統計",
      "字数统计",
      "字數統計",
      "字符数",
      "字符數",
      "字数",
      "字數",
    ],
  },
  // ── general / permissions ──
  {
    id: "general.permissionPolicy",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionPolicy",
    labelKey: "settings.permissionDeep",
    descKeys: [
      "settings.permissionDeepDesc",
      "settings.permissionCliMode",
      "settings.section.permissions",
      "policy.ask",
      "policy.accept_edits",
      "policy.allow_for_session",
      "policy.auto",
      "policy.dont_ask",
      "policy.always_approve",
    ],
    keywords: [
      "permission",
      "yolo",
      "always approve",
      "policy",
      "permission-mode",
      "acceptEdits",
      "bypassPermissions",
      "dontAsk",
      "权限",
      "權限",
      "权限策略",
      "權限策略",
      "权限模式",
      "權限模式",
      "全自动批准",
      "全自動批准",
      "总是批准",
      "總是批准",
    ],
  },
  {
    id: "general.cliPermissionMode",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-cliPermissionModeAdvanced",
    labelKey: "settings.permissionCliAdvanced",
    descKeys: [
      "settings.permissionCliAdvancedDesc",
      "settings.permissionCliAdvancedHint",
      "cliPermission.default",
      "cliPermission.acceptEdits",
      "cliPermission.auto",
      "cliPermission.dontAsk",
      "cliPermission.bypassPermissions",
      "cliPermission.plan",
    ],
    keywords: [
      "permission-mode",
      "cli",
      "default",
      "acceptEdits",
      "auto",
      "dontAsk",
      "bypassPermissions",
      "plan",
      "yolo",
      "权限模式",
      "權限模式",
      "命令行权限",
      "命令行權限",
      "自动接受编辑",
      "自動接受編輯",
    ],
  },
  {
    id: "general.sandbox",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-sandbox",
    labelKey: "settings.sandboxProfile",
    descKeys: [
      "settings.sandboxProfileDesc",
      "settings.sandbox.off",
      "settings.sandbox.off.help",
      "settings.sandbox.workspace",
      "settings.sandbox.workspace.help",
      "settings.sandbox.readOnly",
      "settings.sandbox.readOnly.help",
      "settings.sandbox.strict",
      "settings.sandbox.strict.help",
      "settings.sandbox.devbox",
      "settings.sandbox.devbox.help",
      "settings.sandbox.softFail.cliMissing",
      "settings.sandbox.softFail.cliUnsupported",
      "settings.sandbox.softFail.platform",
      "settings.sandbox.softFail.disabled",
      "settings.sandbox.networkLinuxOnly",
      "settings.sandbox.recommendedNote",
      "settings.sandbox.recommendedDaily",
      "settings.sandbox.appDefaultNote",
      "settings.sandbox.linuxUserns",
      "settings.sandbox.leaderMutex",
      "settings.sandbox.openGuide",
      "settings.sandbox.openGuide.desc",
      "settings.section.permissions",
    ],
    keywords: [
      "sandbox",
      "landlock",
      "seatbelt",
      "isolation",
      "devbox",
      "workspace sandbox",
      "read-only",
      "strict sandbox",
      "soft-fail",
      "GROK_SANDBOX",
      "--sandbox",
      "userns",
      "bubblewrap",
      "SANDBOX_BLOCKED",
      "leader",
      "wizard",
      "沙箱",
      "隔离",
      "沙箱設定",
      "沙箱配置",
    ],
  },
  {
    id: "general.permissionRules",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionRules",
    labelKey: "settings.section.permissions",
    keywords: [
      "rules",
      "permission rules",
      "权限规则",
      "權限規則",
      "规则",
      "規則",
    ],
  },
  {
    id: "general.permissionTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionTimeout",
    labelKey: "settings.permissionTimeout",
    descKeys: [
      "settings.permissionTimeoutDesc",
      "settings.permissionTimeout.off",
      "settings.section.permissions",
    ],
    keywords: [
      "auto-deny",
      "timeout",
      "permission timeout",
      "auto deny",
      "自动拒绝",
      "超时",
    ],
  },
  {
    id: "general.askUserTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-askUserTimeout",
    labelKey: "settings.askUserTimeout",
    descKeys: [
      "settings.askUserTimeoutDesc",
      "settings.askUserTimeout.off",
      "settings.section.permissions",
      "askUser.title",
    ],
    keywords: [
      "ask user",
      "ask question",
      "questionnaire",
      "timeout",
      "auto-dismiss",
      "auto cancel",
      "ask_user_question",
      "提问超时",
      "问卷",
      "自动忽略",
      "超时",
    ],
  },
  // ── general / agent ──
  {
    id: "general.maxAgentTurns",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-maxAgentTurns",
    labelKey: "settings.maxAgentTurns",
    descKeys: ["settings.maxAgentTurnsDesc", "settings.section.agent"],
    keywords: ["max turns", "turns", "最大轮数", "最大輪數", "轮数上限", "輪數上限"],
  },
  {
    id: "general.backgroundWaitPolicy",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-backgroundWait",
    labelKey: "settings.backgroundWaitPolicy",
    descKeys: [
      "settings.backgroundWaitPolicyDesc",
      "settings.backgroundWait.wait",
      "settings.backgroundWait.noWait",
      "settings.backgroundWait.timeout",
      "settings.backgroundWaitTimeout",
      "settings.backgroundWaitTimeoutDesc",
      "settings.section.agent",
    ],
    keywords: [
      "background wait",
      "no-wait-for-background",
      "background-wait-timeout",
      "headless wait",
      "background tasks",
      "wait for background",
      "后台等待",
      "背景等待",
      "不等待后台",
      "bash timeout",
      "timeout_secs",
      "前台命令超时",
      "前景命令逾時",
      "headless only",
      "不是 bash 超时",
    ],
  },
  {
    id: "general.preferredAgent",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-preferredAgent",
    labelKey: "settings.preferredAgent",
    descKeys: [
      "settings.preferredAgentDesc",
      "settings.preferredAgent.apply.note",
      "settings.preferredAgent.apply.softRespawn",
      "settings.preferredAgent.apply.nextMessage",
      "settings.preferredAgent.apply.invalidChars",
    ],
    keywords: [
      "preferred agent",
      "agent definition",
      "--agent",
      "soft-respawn",
      "spawn",
      "首选代理",
      "首選代理",
      "指定代理",
      "代理定义",
      "代理定義",
      "指定 agent",
    ],
  },
  {
    id: "general.agentProfilePath",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentProfilePath",
    labelKey: "settings.agentProfilePath",
    descKeys: [
      "settings.agentProfilePathDesc",
      "settings.agentProfilePathBrowse",
      "settings.agentProfilePathClear",
    ],
    keywords: [
      "agent profile",
      "agent-profile",
      "profile path",
      "agent profile path",
      "profile 文件",
      "profile 路徑",
      "agent profile 路径",
    ],
  },
  {
    id: "general.configTomlView",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlView",
    labelKey: "settings.configTomlView",
    descKeys: [
      "settings.configTomlViewDesc",
      "settings.configTomlView.open",
      "settings.configTomlView.redactNote",
      "settings.configTomlView.sharedWarning",
    ],
    keywords: [
      "config.toml",
      "agent config",
      "view config",
      "config view",
      "redacted config",
      "agent-home config",
      "配置文件",
      "查看配置",
      "config 檢視",
    ],
  },
  {
    id: "general.agentsJson",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentsJson",
    labelKey: "settings.agentsJson",
    descKeys: [
      "settings.agentsJsonDesc",
      "settings.agentsJsonPlaceholder",
      "settings.agentsJsonInvalid",
      "settings.agentsJsonApply",
      "settings.agentsJsonClear",
    ],
    keywords: [
      "agents json",
      "--agents",
      "inline agents",
      "subagent definitions",
      "agents JSON",
      "内联 agents",
      "內聯 agents",
      "子代理 JSON",
    ],
  },
  {
    id: "general.experimentalMemory",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-experimentalMemory",
    labelKey: "settings.experimentalMemory",
    descKeys: ["settings.experimentalMemoryDesc"],
    keywords: ["memory", "记忆", "記憶", "实验性记忆", "實驗性記憶"],
  },
  {
    id: "general.compactionMode",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionMode",
    labelKey: "settings.compactionMode",
    descKeys: [
      "settings.compactionModeDesc",
      "settings.compactionMode.summary",
      "settings.compactionMode.transcript",
      "settings.compactionMode.segments",
      "settings.compactionMode.summary.help",
      "settings.compactionMode.transcript.help",
      "settings.compactionMode.segments.help",
      "settings.compactionApply.note",
      "settings.compactionApply.softRespawn",
      "settings.compactionApply.nextSpawn",
      "settings.compactionApply.unsupported",
    ],
    keywords: [
      "compaction",
      "compaction mode",
      "compact mode",
      "--compaction-mode",
      "GROK_COMPACTION_MODE",
      "summary",
      "transcript",
      "segments",
      "soft-respawn",
      "soft respawn",
      "next spawn",
      "压缩模式",
      "壓縮模式",
    ],
  },
  {
    id: "general.compactionDetail",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionDetail",
    labelKey: "settings.compactionDetail",
    descKeys: [
      "settings.compactionDetailDesc",
      "settings.compactionDetail.none",
      "settings.compactionDetail.minimal",
      "settings.compactionDetail.balanced",
      "settings.compactionDetail.verbose",
      "settings.compactionDetail.help",
      "settings.compactionApply.note",
    ],
    keywords: [
      "compaction detail",
      "segments detail",
      "--compaction-detail",
      "GROK_COMPACTION_DETAIL",
      "minimal",
      "balanced",
      "verbose",
      "soft-respawn",
      "分段细节",
      "分段細節",
    ],
  },
  {
    id: "general.twoPassCompaction",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-twoPassCompaction",
    labelKey: "settings.twoPassCompaction",
    descKeys: ["settings.twoPassCompactionDesc"],
    keywords: [
      "two pass compaction",
      "two-pass",
      "prefire",
      "two_pass_compaction_enabled",
      "GROK_TWO_PASS_COMPACTION",
      "hierarchical compact",
      "双遍压缩",
      "雙遍壓縮",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.memoryBrowser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryBrowser",
    labelKey: "settings.memoryOps",
    descKeys: [
      "settings.memoryOpsDesc",
      "settings.memoryBrowser",
      "settings.memoryBrowserDesc",
      "settings.memoryBrowser.off",
      "settings.memoryBrowser.filterEmpty",
      "settings.memoryBrowser.filterEmptyHintKind",
      "settings.memoryBrowser.searchEmptyHint",
      "settings.memoryBrowser.searchEmptyHintKeyword",
      "settings.memoryBrowser.searchEmptyHintHybridUnavailable",
      "settings.memoryBrowser.emptyHint",
      "settings.clearWorkspaceMemory",
      "settings.memoryBrowser.searchMode.appKeyword",
      "settings.memoryBrowser.searchMode.hybridUnavailable",
      "settings.memoryBrowser.searchKind.hybridUnavailable",
      "settings.memoryBrowser.embedUnsetHint",
      "settings.memoryBrowser.hybridUnavailableHint",
      "settings.memoryOps.mode.appKeyword",
      "settings.memoryOps.mode.hybridUnavailable",
      "settings.memoryOps.mode.memoryOff",
      "settings.memoryOps.hybridUnavailableHint",
      "settings.memoryOps.clear.workspace",
      "settings.memoryOps.clear.global",
      "settings.memoryOps.clear.all",
      "settings.memoryOps.dream",
      "settings.memoryOps.watcher",
      "settings.memoryOps.presenceNote",
    ],
    keywords: [
      "memory browser",
      "memory ops",
      "memory operations",
      "MEMORY.md",
      "workspace memory",
      "global memory",
      "clear memory",
      "memory clear",
      "browse memory",
      "memory filter",
      "memory search",
      "hybrid search",
      "hybrid unavailable",
      "content search",
      "keyword only",
      "no embeddings",
      "reveal",
      "clear memory",
      "clear all memory",
      "dream",
      "watcher",
      "记忆",
      "記憶",
      "memory files",
      "记忆搜索",
      "記憶搜尋",
      "混合检索",
      "混合檢索",
      "embedding",
      "keyword search",
      "kind filter",
      "记忆操作中心",
      "記憶操作中心",
    ],
  },
  {
    id: "general.memoryEmbed",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryEmbed",
    labelKey: "settings.memoryEmbed",
    descKeys: [
      "settings.memoryEmbedDesc",
      "settings.memoryEmbed.model",
      "settings.memoryEmbed.mmr",
      "settings.memoryEmbed.dream",
      "settings.memoryEmbed.embeddingEmpty",
      "settings.memoryEmbed.sharedWarning",
    ],
    keywords: [
      "memory embedding",
      "embedding model",
      "memory_embedding_model",
      "memory search",
      "mmr",
      "memory_mmr",
      "dream",
      "temporal decay",
      "vector search",
      "hybrid search",
      "memory.embed",
      "记忆 embedding",
      "記憶 embedding",
      "向量",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseIndexing",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseIndexing",
    labelKey: "settings.codebaseIndexing",
    descKeys: [
      "settings.codebaseIndexingDesc",
      "settings.codebaseIndexing.enable",
      "settings.codebaseIndexing.enableDesc",
      "settings.codebaseIndexing.noEmbeddings",
      "settings.codebaseIndexing.sharedWarning",
      "settings.codebaseIndexing.unsetDefaultHint",
      "settings.codeGraph.appSearchRemainsKeyword",
      "settings.codeGraph.mode.graphUnavailable",
    ],
    keywords: [
      "codebase indexing",
      "codebase_indexing",
      "code graph",
      "code-nav",
      "features.codebase_indexing",
      "[features] codebase_indexing",
      "index",
      "代码库索引",
      "程式碼庫索引",
      "代码图",
      "程式碼圖",
      "keyword vs graph",
      "not embeddings",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseSearch",
    labelKey: "settings.codebaseSearch",
    descKeys: [
      "settings.codebaseSearchDesc",
      "settings.codebaseSearch.noEmbeddings",
      "settings.codebaseSearch.idleHint",
      "settings.codebaseSearch.mode.all",
      "settings.codebaseSearch.mode.name",
      "settings.codebaseSearch.mode.content",
      "settings.codeGraph.chip.appKeyword",
      "settings.codeGraph.chip.graphUnavailable",
    ],
    keywords: [
      "codebase search",
      "project search",
      "file search",
      "content search",
      "rg",
      "ripgrep",
      "keyword search",
      "find in files",
      "code graph",
      "keyword vs graph",
      "代码库搜索",
      "專案搜尋",
      "文件搜索",
      "內容搜尋",
      "代码图",
      "程式碼圖",
      "not embeddings",
    ],
  },
  {
    id: "general.subagents",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagents",
    labelKey: "settings.subagentsEnabled",
    descKeys: ["settings.subagentsEnabledDesc"],
    keywords: [
      "subagents",
      "sub-agent",
      "子代理",
      "子智能体",
      "子智能體",
      "启用子代理",
      "啟用子代理",
    ],
  },
  {
    id: "general.subagentWorktreeSnapshot",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagentWtSnap",
    labelKey: "settings.subagentWorktreeSnapshot",
    descKeys: [
      "settings.subagentWorktreeSnapshotDesc",
      "tasks.subagentWtSnapNote",
    ],
    keywords: [
      "subagent worktree snapshot",
      "subagent_worktree_snapshot_enabled",
      "GROK_SUBAGENT_WORKTREE_SNAPSHOT",
      "worktree snapshot",
      "subagent snapshot",
      "子代理 worktree 快照",
      "子代理工作樹快照",
      "快照",
    ],
  },
  {
    id: "general.autoWake",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-autoWake",
    labelKey: "settings.autoWake",
    descKeys: ["settings.autoWakeDesc"],
    keywords: [
      "auto wake",
      "auto-wake",
      "auto_wake_enabled",
      "GROK_CONFIG",
      "features.auto_wake",
      "background task wake",
      "synthetic turn",
      "task completed",
      "monitor wake",
      "自动唤醒",
      "自動喚醒",
      "后台任务",
      "背景任務",
      "共享模式",
    ],
  },
  {
    id: "general.configTomlEdit",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlEdit",
    labelKey: "settings.configTomlEdit",
    descKeys: [
      "settings.configTomlEditDesc",
      "settings.configTomlEdit.sharedWarning",
      "settings.configTomlEdit.redactNote",
    ],
    keywords: [
      "config.toml",
      "agent-home",
      "config edit",
      "section edit",
      "permission_mode",
      "yolo",
      "subagents",
      "memory",
      "workflows",
      "workflows_enabled",
      "auto_wake",
      "auto_wake_enabled",
      "two_pass_compaction",
      "lsp_tools",
      "codebase_indexing",
      "remote_fetch",
      "features",
      "GROK_HOME",
      "配置编辑",
      "配置編輯",
      "agent-home 配置",
      "工作流",
      "自动唤醒",
      "自動喚醒",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.plan",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-planEnabled",
    labelKey: "settings.planEnabled",
    descKeys: ["settings.planEnabledDesc"],
    keywords: ["plan mode", "计划模式", "計劃模式", "规划模式", "規劃模式"],
  },
  {
    id: "general.todoGate",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-todoGate",
    labelKey: "settings.todoGate",
    descKeys: [
      "settings.todoGateDesc",
      "settings.todoGate.softRespawnNote",
      "settings.todoGate.activity.na",
      "settings.todoGateMaxFires",
      "settings.todoGateMaxFiresDesc",
      "settings.todoGateMaxFires.effective",
      "settings.todoGateMaxFires.independent",
      "settings.todoGateMaxFires.shared",
      "settings.todoGateMaxFires.inactive",
    ],
    keywords: [
      "todo gate",
      "todogate",
      "--todo-gate",
      "todo_gate_enabled",
      "todo_gate_max_fires_per_prompt",
      "max fires",
      "pending todos",
      "turn-end",
      "TodoGate",
      "soft-respawn",
      "gate activity",
      "待办门控",
      "待辦門控",
      "todo 门控",
      "最大触发",
      "最大觸發",
    ],
  },
  {
    id: "general.disableWebSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disableWebSearch",
    labelKey: "settings.disableWebSearch",
    descKeys: ["settings.disableWebSearchDesc"],
    keywords: [
      "web search",
      "禁用联网搜索",
      "禁用聯網搜索",
      "关闭网页搜索",
      "關閉網頁搜索",
      "联网搜索",
      "聯網搜索",
    ],
  },
  {
    id: "general.noAskUser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-noAskUser",
    labelKey: "settings.noAskUser",
    descKeys: ["settings.noAskUserDesc"],
    keywords: [
      "no ask user",
      "no-ask-user",
      "ask_user_question",
      "ask user",
      "questionnaire",
      "0.2.117",
      "不问用户",
      "不问用户问题",
      "禁用提问",
    ],
  },
  {
    id: "general.allowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-allowedTools",
    labelKey: "settings.allowedTools",
    descKeys: [
      "settings.allowedToolsDesc",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "allowed tools",
      "allowlist",
      "tools allow",
      "--tools",
      "web_search",
      "run_terminal_command",
      "tool allow",
      "允许工具",
      "允許工具",
      "工具白名单",
      "工具白名單",
      "允许列表",
      "允許列表",
    ],
  },
  {
    id: "general.disallowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disallowedTools",
    labelKey: "settings.disallowedTools",
    descKeys: [
      "settings.disallowedToolsDesc",
      "settings.disallowedTools.webCovered",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "disallowed tools",
      "deny tools",
      "web_search",
      "web_fetch",
      "run_terminal_command",
      "tool deny",
      "禁用工具",
      "工具黑名单",
      "工具黑名單",
      "拒绝工具",
      "拒絕工具",
    ],
  },
  {
    id: "general.useLeader",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-useLeader",
    labelKey: "settings.useLeader",
    descKeys: ["settings.useLeaderDesc"],
    keywords: ["leader", "领导者", "領導者", "主从调度", "主從調度"],
  },
  // ── general / app ──
  {
    id: "general.language",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-language",
    labelKey: "settings.language",
    descKeys: ["settings.languageDesc", "settings.section.general"],
    keywords: [
      "language",
      "locale",
      "中文",
      "english",
      "system",
      "跟随系统",
      "跟隨系統",
    ],
  },
  {
    id: "general.sessionDataMode",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sessionDataMode",
    labelKey: "settings.sessionDataMode",
    descKeys: [
      "settings.sessionDataModeDesc",
      "settings.modeShared",
      "settings.modeIndependent",
      "settings.sessionModeHelp",
      "settings.sessionDataMode.status",
      "settings.sessionDataMode.banner.sharedWithCli",
      "settings.sessionDataMode.banner.noRewriteSecrets",
      "settings.sessionDataMode.banner.conflictPossible",
      "settings.sessionDataMode.risk.noSilentMerge",
      "settings.cliSessions",
    ],
    keywords: [
      "session data",
      "shared",
      "independent",
      "cli sessions",
      "agent-home",
      "GROK_HOME",
      "~/.grok",
      "merge",
      "recycle",
      "no silent merge",
      "会话数据",
      "共享",
      "独立",
    ],
  },
  {
    id: "general.cliSessions",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-cliSessions",
    labelKey: "settings.cliSessions",
    descKeys: [
      "settings.cliSessionsDesc",
      "settings.cliSessionsManage",
      "settings.cliSessionsIndependentNote",
      "settings.cliSessionsImportOpen",
      "settings.cliSessionsDelete",
      "settings.cliSessionsDeleteUnlinked",
      "settings.cliSessionsFilterPlaceholder",
      "settings.cliSessionsSearchViaCli",
      "settings.cliSessionsEmptyCliMissing",
      "settings.cliSessions.clearFilters",
      "settings.cliSessions.filterLinked",
      "settings.cliSessions.filterUnlinked",
      "settings.cliSessions.err.cli_missing",
    ],
    keywords: [
      "cli sessions",
      "import session",
      "manage sessions",
      "agent session id",
      "resume",
      "delete session",
      "search sessions",
      "first prompt",
      "linked",
      "unlinked",
      "clear filters",
      "cli missing",
      "CLI 会话",
      "管理会话",
      "导入会话",
      "删除会话",
      "搜索会话",
      "首条提示",
      "已关联",
      "未关联",
      "清除筛选",
    ],
  },
  {
    id: "general.voiceHotkeyEnabled",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceHotkeyEnabled",
    labelKey: "settings.voiceHotkeyEnabled",
    descKeys: ["settings.voiceHotkeyEnabledDesc", "settings.section.voice"],
    keywords: [
      "voice",
      "hotkey",
      "shortcut",
      "live voice",
      "keyboard",
      "语音",
      "快捷键",
      "实时语音",
    ],
  },
  {
    id: "general.voiceId",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceId",
    labelKey: "settings.voiceId",
    descKeys: ["settings.voiceIdDesc", "settings.section.voice"],
    keywords: ["voice", "speaker", "tts", "语音", "音色"],
  },
  {
    id: "general.voiceDictationAutoSend",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceDictationAutoSend",
    labelKey: "settings.voiceDictationAutoSend",
    descKeys: ["settings.voiceDictationAutoSendDesc"],
    keywords: ["dictation", "auto send", "听写", "语音输入"],
  },
  {
    id: "general.voiceKeepAgentsOnEnd",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceKeepAgentsOnEnd",
    labelKey: "settings.voiceKeepAgentsOnEnd",
    descKeys: ["settings.voiceKeepAgentsOnEndDesc"],
    keywords: ["voice", "keep agents", "语音", "保留"],
  },
  {
    id: "general.sttEngine",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sttEngine",
    labelKey: "settings.sttEngine",
    descKeys: [
      "settings.sttEngineDesc",
      "settings.section.voice",
    ],
    keywords: [
      "dictation",
      "stt",
      "speech to text",
      "transcription",
      "openai compatible",
      "custom endpoint",
      "base url",
      "provider template",
      "preset",
      "local",
      "faster-whisper",
      "groq",
      "whisper",
      "mistral",
      "voxtral",
      "简体",
      "繁体",
      "繁体中文",
      "simplified",
      "traditional",
      "听写",
      "语音转文字",
      "语音输入",
      "自定义端点",
      "提供方",
      "模板",
    ],
  },
  {
    id: "general.keychain",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keychain",
    labelKey: "settings.storeApiKeysInKeychain",
    descKeys: ["settings.storeApiKeysInKeychainDesc"],
    keywords: [
      "keychain",
      "api key",
      "secrets",
      "钥匙串",
      "鑰匙串",
      "密钥串",
      "密鑰串",
      "密钥",
      "密鑰",
      "保险箱",
      "保險箱",
    ],
  },
  {
    id: "general.clearMemory",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-clearMemory",
    labelKey: "settings.clearWorkspaceMemory",
    descKeys: ["settings.clearWorkspaceMemoryDesc"],
    keywords: [
      "clear memory",
      "workspace memory",
      "清除记忆",
      "清除記憶",
      "清空记忆",
      "清空記憶",
      "工作区记忆",
      "工作區記憶",
    ],
  },
  {
    id: "general.reopenLastSession",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-reopenLastSession",
    labelKey: "settings.reopenLastSession",
    descKeys: ["settings.reopenLastSessionDesc"],
    keywords: [
      "reopen",
      "restore session",
      "恢复上次会话",
      "恢復上次會話",
      "重新打开",
      "重新打開",
      "恢复会话",
      "恢復會話",
    ],
  },
  {
    id: "general.closeToTray",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-closeToTray",
    labelKey: "settings.closeToTray",
    descKeys: ["settings.closeToTrayDesc"],
    keywords: ["tray", "close", "minimize", "托盘", "系統匣", "关闭"],
  },
  {
    id: "general.keepTrayForSchedules",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keepTrayForSchedules",
    labelKey: "settings.keepTrayForSchedules",
    descKeys: ["settings.keepTrayForSchedulesDesc"],
    keywords: [
      "tray",
      "schedules",
      "automations",
      "background",
      "keep",
      "scheduled",
      "托盘",
      "已安排",
      "调度",
      "系统匣",
      "排程",
    ],
  },
  {
    id: "general.trayBusyBadge",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-trayBusyBadge",
    labelKey: "settings.trayBusyBadge",
    descKeys: [
      "settings.trayBusyBadgeDesc",
      "settings.trayBusyBadge.status.off",
      "settings.trayBusyBadge.status.idle",
      "settings.trayBusyBadge.status.busy",
      "settings.trayBusyBadge.status.capped",
    ],
    keywords: [
      "badge",
      "dock",
      "tray",
      "busy",
      "unread",
      "count",
      "角标",
      "徽章",
      "托盘",
      "忙碌",
      "未读",
      "未讀",
      "系統匣",
      "notify",
      "notification",
    ],
  },
  {
    id: "general.winTaskbarOverlay",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-winTaskbarOverlay",
    labelKey: "settings.winTaskbarOverlay",
    descKeys: ["settings.winTaskbarOverlayDesc"],
    keywords: [
      "windows",
      "taskbar",
      "overlay",
      "badge",
      "unread",
      "count",
      "任务栏",
      "工作列",
      "角标",
      "未读",
      "未讀",
    ],
  },
  {
    id: "general.notifyHonesty",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyHonesty",
    labelKey: "settings.notify.honesty.title",
    descKeys: [
      "settings.notify.honesty.desc",
      "settings.notify.honesty.ok",
      "settings.notify.honesty.osDenied",
      "settings.notify.honesty.osDefault",
      "settings.notify.honesty.osUnsupported",
      "settings.notify.honesty.prefsOff",
      "settings.notify.honesty.quietHours",
    ],
    keywords: [
      "notification",
      "desktop",
      "permission",
      "os",
      "quiet hours",
      "dnd",
      "notify",
      "桌面通知",
      "系统权限",
      "免打扰",
      "通知權限",
    ],
  },
  {
    id: "general.launchAtLogin",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-launchAtLogin",
    labelKey: "settings.launchAtLogin",
    descKeys: ["settings.launchAtLoginDesc"],
    keywords: [
      "launch",
      "login",
      "startup",
      "autostart",
      "boot",
      "automation",
      "scheduled",
      "schedule",
      "daemon",
      "background",
      "开机",
      "登录",
      "啟動",
      "登入",
      "自动化",
      "已安排",
      "排程",
      "后台",
      "背景",
    ],
  },
  {
    id: "general.windowAlwaysOnTop",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-windowAlwaysOnTop",
    labelKey: "settings.windowAlwaysOnTop",
    descKeys: ["settings.windowAlwaysOnTopDesc"],
    keywords: [
      "always on top",
      "pin",
      "float",
      "stay on top",
      "置顶",
      "置頂",
      "窗口",
      "視窗",
    ],
  },
  {
    id: "general.notifyOnTurnDone",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnTurnDone",
    labelKey: "settings.notifyOnTurnDone",
    descKeys: ["settings.notifyOnTurnDoneDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "turn done",
      "notify",
      "桌面通知",
      "完成通知",
    ],
  },
  {
    id: "general.notifyOnPermission",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnPermission",
    labelKey: "settings.notifyOnPermission",
    descKeys: ["settings.notifyOnPermissionDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "permission",
      "notify",
      "桌面通知",
      "授权通知",
    ],
  },
  {
    id: "general.notifySound",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifySound",
    labelKey: "settings.notifySound",
    descKeys: ["settings.notifySoundDesc"],
    keywords: [
      "notification",
      "sound",
      "beep",
      "audio",
      "alert",
      "notify",
      "通知声音",
      "提示音",
    ],
  },
  {
    id: "general.notifyQuietHours",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyQuietHours",
    labelKey: "settings.notifyQuietHours",
    descKeys: [
      "settings.notifyQuietHoursDesc",
      "settings.notifyQuietHoursStart",
      "settings.notifyQuietHoursEnd",
      "settings.notifyQuietHours.activeNow",
    ],
    keywords: [
      "quiet hours",
      "do not disturb",
      "dnd",
      "notification",
      "desktop",
      "mute",
      "night",
      "免打扰",
      "勿扰",
      "静音时段",
      "桌面通知",
    ],
  },
  {
    id: "general.stopAllSkipConfirm",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-stopAllSkipConfirm",
    labelKey: "settings.stopAllSkipConfirm",
    descKeys: ["settings.stopAllSkipConfirmDesc"],
    keywords: [
      "stop all",
      "skip confirm",
      "busy sessions",
      "tasks",
      "dashboard",
      "no confirm",
      "全部停止",
      "跳过确认",
      "忙碌会话",
    ],
  },
  {
    id: "general.alwaysQuitWithoutAsking",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-alwaysQuitWithoutAsking",
    labelKey: "settings.alwaysQuitWithoutAsking",
    descKeys: ["settings.alwaysQuitWithoutAskingDesc"],
    keywords: [
      "quit",
      "exit",
      "close",
      "busy",
      "confirm",
      "always quit",
      "without asking",
      "退出",
      "结束",
      "忙碌",
      "确认",
      "不再询问",
    ],
  },
  {
    id: "general.openTarget",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-openTarget",
    labelKey: "settings.openTarget",
    descKeys: [
      "settings.openTargetDesc",
      "settings.openFinder",
      "settings.openTargetEmpty",
      "settings.openTargetPreferredMissing",
      "settings.openTargetUnavailable",
    ],
    keywords: [
      "open in",
      "finder",
      "editor",
      "no editors",
      "preferred editor",
      "打开方式",
      "打開方式",
      "外部编辑器",
      "外部編輯器",
      "首选编辑器",
      "首選編輯器",
    ],
  },
];
