import type { SettingsEntry } from "../types";

/** Settings catalog entries — runtime / tools section. */
export const RUNTIME_TOOLS_ENTRIES: readonly SettingsEntry[] = [
  {
    id: "runtime.workflows",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-workflows",
    labelKey: "settings.workflows",
    descKeys: [
      "settings.workflowsDesc",
      "settings.workflowsHonesty",
      "settings.workflows.runHonesty",
      "settings.workflows.authorHint",
      "settings.workflows.openDocs",
      "settings.workflows.discovered",
      "settings.workflows.noneFound",
      "settings.workflows.run.smoke",
      "settings.workflows.run.launch",
      "settings.workflows.create",
      "settings.workflows.history",
      "settings.workflows.history.honesty",
    ],
    keywords: [
      "workflows",
      "workflow",
      "workflows_enabled",
      "rhai",
      "create-workflow",
      "/workflows",
      "/workflow",
      "orchestration",
      "multi-agent pipeline",
      "validate_only",
      "smoke",
      "headless",
      "workflow tool",
      "template",
      "scaffold",
      "recent runs",
      "history",
      "工作流",
      "工作流程",
      "冒烟",
      "冒煙",
      "模板",
      "最近运行",
      "最近執行",
    ],
  },
  {
    id: "runtime.doctor",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-doctor",
    labelKey: "doctor.title",
    descKeys: ["settings.doctorDesc", "settings.runDoctor"],
    keywords: ["doctor", "diagnose", "诊断", "診斷", "体检", "體檢", "自检", "自檢"],
  },
  {
    id: "runtime.traces",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-traces",
    labelKey: "session.tracesTitle",
    descKeys: [
      "session.tracesDesc",
      "session.exportTraceLocal",
      "session.exportTraceUpload",
    ],
    keywords: [
      "trace",
      "traces",
      "session trace",
      "grok trace",
      "export history",
      "诊断",
      "追踪",
    ],
  },
  {
    id: "runtime.reliability",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-reliability",
    labelKey: "reliability.title",
    descKeys: [
      "reliability.settingsDesc",
      "reliability.openFromSettings",
      "reliability.audit.title",
      "reliability.audit.lead",
    ],
    keywords: [
      "reliability",
      "observability",
      "busy",
      "stall",
      "error deck",
      "support zip",
      "audit",
      "ledger",
      "tool audit",
      "permission log",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.auditRetention",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-auditRetention",
    labelKey: "reliability.audit.retention",
    descKeys: [
      "reliability.audit.retentionDesc",
      "reliability.audit.retention.7",
      "reliability.audit.retention.30",
      "reliability.audit.retention.90",
      "reliability.audit.retention.unlimited",
    ],
    keywords: [
      "audit",
      "ledger",
      "retention",
      "prune",
      "tool audit",
      "permission log",
      "7 days",
      "30 days",
      "90 days",
      "unlimited",
      "保留",
      "留存",
      "清理",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.batchAgents",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-batch-agents",
    labelKey: "batchAgents.title",
    descKeys: [
      "batchAgents.settingsDesc",
      "batchAgents.openFromSettings",
      "batchAgents.hint",
    ],
    keywords: [
      "batch",
      "batch agents",
      "multi project",
      "multi-project",
      "dispatch",
      "fan out",
      "headless summary",
      "same prompt",
      "批量",
      "多项目",
      "派发",
    ],
  },
  {
    id: "runtime.costRollup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-cost-rollup",
    labelKey: "costRollup.title",
    descKeys: [
      "costRollup.settingsDesc",
      "costRollup.disclaimer",
      "costRollup.exportCopy",
      "costRollup.clearFilters",
      "costRollup.clear",
    ],
    keywords: [
      "cost",
      "rollup",
      "token usage",
      "estimate",
      "billing",
      "project cost",
      "session cost",
      "export summary",
      "filter",
      "clear samples",
      "费用",
      "费用汇总",
      "用量",
      "token",
      "会话费用",
      "筛选",
      "清除样本",
      "匯出",
      "篩選",
    ],
  },
  {
    id: "runtime.streamingMessagesJson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-smj",
    labelKey: "smj.title",
    descKeys: ["smj.settingsDesc", "smj.lead", "smj.formatHint"],
    keywords: [
      "streaming-messages-json",
      "streaming messages",
      "ndjson",
      "output-format",
      "anthropic messages",
      "tool_use",
      "headless probe",
      "0.2.117",
      "流式消息",
      "消息 JSON",
    ],
  },
  {
    id: "runtime.streamAcpNdjson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-stream-acp-ndjson",
    labelKey: "streamAcpNdjson.title",
    descKeys: [
      "streamAcpNdjson.settingsDesc",
      "streamAcpNdjson.lead",
    ],
    keywords: [
      "streaming-json",
      "streaming-messages-json",
      "ndjson",
      "acp",
      "session/update",
      "headless probe",
      "diagnostics",
      "0.2.117",
      "output-format",
      "诊断",
      "流式",
    ],
  },
  {
    id: "runtime.inspect",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-inspect",
    labelKey: "inspect.title",
    descKeys: ["inspect.desc"],
    keywords: [
      "inspect",
      "project inspect",
      "项目检查",
      "項目檢查",
      "项目体检",
      "項目體檢",
      "工程检视",
    ],
  },
  {
    id: "runtime.prHub",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-prHub",
    labelKey: "prHub.title",
    descKeys: ["prHub.desc"],
    keywords: [
      "pull request",
      "pull requests",
      "PR",
      "PRs",
      "gh pr",
      "github pr",
      "checks",
      "comments",
      "reviews",
      "conversation",
      "mergeable",
      "CI",
      "PR hub",
      "拉取请求",
      "拉取請求",
      "合并",
      "合併",
      "评论",
      "評論",
      "检查",
      "檢查",
    ],
  },
  {
    id: "runtime.managedSetup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-managedSetup",
    labelKey: "managedSetup.title",
    descKeys: [
      "managedSetup.desc",
      "managedSetup.authHint",
      "managedSetup.statusTitle",
      "managedSetup.sigHint",
      "managedSetup.sig.cardTitle",
      "managedSetup.recovery.presentUnverified",
    ],
    keywords: [
      "managed setup",
      "grok setup",
      "managed_config",
      "managed config",
      "deployment key",
      "GROK_DEPLOYMENT_KEY",
      "signature",
      "signature verified",
      "present unverified",
      "presence only",
      "managed_config.sig",
      "requirements.toml",
      "verify_ok",
      "托管",
      "託管",
      "部署密钥",
      "部署金鑰",
      "签名",
      "簽名",
      "验签",
      "驗簽",
      "仅存在性",
      "僅存在性",
    ],
  },
];
