import type { SettingsEntry } from "../types";

/** Settings catalog entries — shortcuts section. */
export const SHORTCUTS_ENTRIES: readonly SettingsEntry[] = [
  // ── shortcuts ──
  {
    id: "shortcuts.table",
    section: "shortcuts",
    anchorId: "settings-anchor-shortcuts",
    labelKey: "settings.shortcuts.title",
    descKeys: [
      "settings.shortcuts.desc",
      "settings.shortcuts.group.workbench",
      "settings.shortcuts.group.navigation",
      "settings.shortcuts.group.view",
      "settings.shortcuts.group.diagnostics",
      "settings.shortcuts.group.input",
      "settings.shortcuts.record",
      "settings.shortcuts.resetAll",
      "settings.shortcuts.resetAllTitle",
      "settings.shortcuts.filterPlaceholder",
      "settings.shortcuts.conflictsTitle",
      "settings.shortcuts.ignoreCrossScope",
      "settings.shortcuts.scope.global",
      "settings.shortcuts.scope.chatFocus",
    ],
    keywords: [
      "keyboard",
      "hotkey",
      "shortcut",
      "quit",
      "ctrl+q",
      "ctrl+tab",
      "recent chat",
      "mru",
      "switch chat",
      "最近对话",
      "切换会话",
      "最近對話",
      "切換會話",
      "zoom",
      "newline",
      "prompt history",
      "remap",
      "binding",
      "record",
      "filter",
      "search",
      "conflict",
      "reset all",
      "scope",
      "global",
      "chat-focus",
      "chord",
      "keymap",
      "改键",
      "快捷键",
      "缩放",
      "换行",
      "录制",
      "筛选",
      "冲突",
      "全部重置",
      "范围",
      "改鍵",
      "快捷鍵",
      "錄製",
      "篩選",
      "衝突",
      "全部重設",
      "範圍",
    ],
  },
];
