/**
 * Props contract for WorkbenchSettingsStage — the settings overlay stage.
 * Extracted from the stage component so the 223-field interface lives in
 * its own module (files_ge_1000 gate) and can be imported by tests.
 *
 * Field types were inferred from the real AppWorkbench call site via the
 * TS checker; oversized inline shapes use named types
 * (CliInfoState, CompactionModeId / CompactionDetailId).
 */
import type { Dispatch, RefObject, SetStateAction } from "react";
import { createT } from "@/i18n";
import type { LocalePreference } from "@/i18n";
import type { Project, SessionRow } from "@/lib/app/sidebarModels";
import type { CliInfoState } from "@/lib/cliVersionStatus";
import type { CompactionModeId, CompactionDetailId } from "@/lib/compactionMode";
import type { SettingsSectionId } from "@/components/SettingsPage";
import type { AccountStatus, SavedAccount } from "@/lib/api/account";
import type { AppDialog } from "@/lib/app/appDialogTypes";
import type { ComposerPrefs } from "@/lib/api/settings";
import type { ModelOption, PermissionPolicyId, ComposerPrefsScope } from "@/lib/grokCatalog";
import type { ProcessLimitEvent } from "@/lib/processBudget";
import type { ProviderBalanceCache } from "@/lib/providerBalanceFormat";
import type { ResourceOpenTarget } from "@/components/resource-viewer/types";
import type { SessionSnapshot } from "@/lib/session/types";
import type { SettingsTabId } from "@/lib/settingsCatalog/types";
import type { SetupFlags } from "@/hooks/useSetupBootGate";
import type { Theme, ThemePreference } from "@/lib/theme";
import type { ThemeScheduleConfig } from "@/lib/themeSchedule";
import type { ThemeSkinId, WallpaperRecord } from "@/lib/themeSkin";
import type { WallpaperClip } from "@/lib/wallpaperClip";
import type { WallpaperFocus } from "@/lib/wallpaperFocus";
import type { MessageTimeFormat } from "@/lib/messageTimeFormatPref";

type TFn = ReturnType<typeof createT>;

export type TrayHandlers = {
  newChat: () => void;
  openSessionById: (_id: string) => void;
  /** Omit section to restore last settings route. */
  openSettings: (_section?: SettingsSectionId) => void;
  openDoctor: () => void;
};

export type WorkbenchSettingsStageProps = {
  account: AccountStatus | null;
  accountBusy: boolean;
  accountHeatmapError: unknown;
  accountLoading: boolean;
  accountProbeError: unknown;
  acpServerAddr: string;
  activeAccountId: string | null;
  activeProject: Project | null;
  agentCatalog: { name: string; source: string; }[];
  agentIdleMinutes: number;
  agentProfilePath: string;
  agentsJson: string;
  allowUnverifiedCliInstall: boolean;
  allowedTools: string[];
  applyComposerPrefs: (prefs: ComposerPrefs, catalog: ModelOption[]) => void;
  applyGlobalSandboxProfile: (nextRaw: string) => void;
  applyPermissionPolicy: (next: PermissionPolicyId) => void;
  applySkinChoice: (next: ThemeSkinId, options?: { applyPreferredTheme?: boolean | undefined; } | undefined) => void;
  applyThemeChoice: (next: ThemePreference) => void;
  applyThemeScheduleChoice: (next: ThemeScheduleConfig) => void;
  applyWallpaperAdjustChoice: (patch: { focus: WallpaperFocus; clip: WallpaperClip | null; duration?: number | undefined; }) => void;
  applyWallpaperChoice: any;
  applyWallpaperMediaSize: (size: { w: number; h: number; }) => void;
  applyWallpaperScrimChoice: (value: number) => void;
  applyWallpaperBlurChoice: (value: number) => void;
  archivedGroups: { id: string | null; name: string; sessions: SessionRow[]; }[];
  askUserTimeoutSec: number;
  auditLedgerRetentionDays: number;
  autoWakeEnabled: boolean;
  availableModels: ModelOption[];
  backgroundWaitPolicy: string;
  backgroundWaitTimeoutSec: number;
  cancelAccountLogin: () => Promise<void>;
  cliAgentSkewRepairing: boolean;
  cliInfo: CliInfoState;
  closeToTray: boolean;
  compactionDetail: CompactionDetailId;
  compactionMode: CompactionModeId;
  confirmArchiveOlderThan: (days: number) => void;
  defaultOpenTarget: string;
  deleteSessionsConfirm: (rows: SessionRow[]) => void;
  disableWebSearch: boolean;
  disallowedTools: string[];
  effectiveProjectPath: string | null;
  experimentalMemory: boolean;
  goalOrchUiEnabled: boolean;
  handleClearAllSessionMutes: () => void;
  handleClearAllSessionUnread: () => void;
  importChatTranscript: () => Promise<void>;
  includePartialMessages: boolean;
  keepTrayForSchedules: boolean;
  lastCliChecksumVerified: boolean | null;
  lastProcessLimit: ProcessLimitEvent | null;
  launchAtLogin: boolean;
  locale: "id" | "en" | "de" | "es" | "fil" | "fr" | "it" | "ja" | "ko" | "pt-BR" | "ru" | "ta" | "uk" | "zh" | "zh-TW";
  localePreference: LocalePreference;
  loginHint: string | null;
  manualCliPath: string;
  maxAgentTurns: number;
  maxConcurrentAgents: number;
  messageTimeFormat: MessageTimeFormat;
  mutedSessionIds: Set<string>;
  navigateSettings: (section?: SettingsSectionId | null | undefined, tab?: string | null | undefined) => void;
  navigateWorkbench: () => void;
  noAskUser: boolean;
  notifyOnPermission: boolean;
  notifyOnTurnDone: boolean;
  notifySound: boolean;
  openAsidePane: () => void;
  openBatchAgents: () => void;
  openDoctor: () => void;
  openReliability: () => void;
  openSandboxWizardGuide: () => void;
  permissionTimeoutSec: number;
  phoneLayout: boolean;
  planEnabled: boolean;
  policy: string;
  prHubHighlightPr: number | null;
  preferredAgent: string;
  prefsScope: ComposerPrefsScope;
  projects: Project[];
  proxyMode: string;
  proxyNoProxy: string;
  proxyUrl: string;
  refreshAccount: (refreshOpts?: { refreshBilling?: boolean | undefined; quiet?: boolean | undefined; includeLocalUsage?: boolean | undefined; isCurrent?: (() => boolean) | undefined; } | undefined) => Promise<void>;
  refreshProviderRoute: () => Promise<void>;
  refreshSessions: () => Promise<void>;
  refreshVoiceGate: () => Promise<void>;
  reopenLastSession: boolean;
  replaceProviderBrandLogo: boolean;
  welcomeMotionEnabled: boolean;
  setWelcomeMotionEnabled: Dispatch<SetStateAction<boolean>>;
  restoreSessions: (rows: SessionRow[]) => Promise<void>;
  runAccountLogin: (method?: "oauth" | "device") => Promise<boolean>;
  runAccountLogout: () => Promise<void>;
  runAddAccount: () => Promise<void>;
  runRemoveAccount: (id: string) => void;
  runSaveAccount: () => Promise<void>;
  runSwitchAccount: (id: string) => Promise<void>;
  sandboxProfile: "off" | "workspace" | "read-only" | "strict" | "devbox";
  savedAccounts: SavedAccount[];
  session: SessionSnapshot;
  sessionDataMode: "shared" | "independent";
  sessions: SessionRow[];
  setAcpServerAddr: Dispatch<SetStateAction<string>>;
  setAgentIdleMinutes: Dispatch<SetStateAction<number>>;
  setAgentProfilePath: Dispatch<SetStateAction<string>>;
  setAgentsJson: Dispatch<SetStateAction<string>>;
  setAllowUnverifiedCliInstall: Dispatch<SetStateAction<boolean>>;
  setAllowedTools: Dispatch<SetStateAction<string[]>>;
  setAppDialog: Dispatch<SetStateAction<AppDialog>>;
  setAskUserTimeoutSec: Dispatch<SetStateAction<number>>;
  setAuditLedgerRetentionDays: Dispatch<SetStateAction<number>>;
  setAutoWakeEnabled: Dispatch<SetStateAction<boolean>>;
  setBackgroundWaitPolicy: Dispatch<SetStateAction<string>>;
  setBackgroundWaitTimeoutSec: Dispatch<SetStateAction<number>>;
  setCliAgentSkewRepairing: Dispatch<SetStateAction<boolean>>;
  setCliInfo: Dispatch<SetStateAction<CliInfoState>>;
  setCloseToTray: Dispatch<SetStateAction<boolean>>;
  setCompactionDetail: Dispatch<SetStateAction<CompactionDetailId>>;
  setCompactionMode: Dispatch<SetStateAction<CompactionModeId>>;
  setDefaultOpenTarget: Dispatch<SetStateAction<string>>;
  setDisableWebSearch: Dispatch<SetStateAction<boolean>>;
  setDisallowedTools: Dispatch<SetStateAction<string[]>>;
  setExperimentalMemory: Dispatch<SetStateAction<boolean>>;
  setGoalOrchUiEnabled: Dispatch<SetStateAction<boolean>>;
  setIncludePartialMessages: Dispatch<SetStateAction<boolean>>;
  setKeepTrayForSchedules: Dispatch<SetStateAction<boolean>>;
  setLaunchAtLogin: Dispatch<SetStateAction<boolean>>;
  setLocale: Dispatch<SetStateAction<"id" | "en" | "de" | "es" | "fil" | "fr" | "it" | "ja" | "ko" | "pt-BR" | "ru" | "ta" | "uk" | "zh" | "zh-TW">>;
  setLocalePreference: Dispatch<SetStateAction<LocalePreference>>;
  setManualCliPath: Dispatch<SetStateAction<string>>;
  setMaxAgentTurns: Dispatch<SetStateAction<number>>;
  setMaxConcurrentAgents: Dispatch<SetStateAction<number>>;
  setMessageTimeFormat: Dispatch<SetStateAction<MessageTimeFormat>>;
  setNoAskUser: Dispatch<SetStateAction<boolean>>;
  setNotifyOnPermission: Dispatch<SetStateAction<boolean>>;
  setNotifyOnTurnDone: Dispatch<SetStateAction<boolean>>;
  setNotifySound: Dispatch<SetStateAction<boolean>>;
  setPermissionTimeoutSec: Dispatch<SetStateAction<number>>;
  setPlanEnabled: Dispatch<SetStateAction<boolean>>;
  setPreferredAgent: Dispatch<SetStateAction<string>>;
  setPrefsScope: Dispatch<SetStateAction<ComposerPrefsScope>>;
  setProviderBalanceCache: Dispatch<SetStateAction<ProviderBalanceCache | null>>;
  setProxyMode: Dispatch<SetStateAction<string>>;
  setProxyNoProxy: Dispatch<SetStateAction<string>>;
  setProxyUrl: Dispatch<SetStateAction<string>>;
  setReopenLastSession: Dispatch<SetStateAction<boolean>>;
  setReplaceProviderBrandLogo: Dispatch<SetStateAction<boolean>>;
  setResourceOpenTarget: Dispatch<SetStateAction<ResourceOpenTarget | null>>;
  setSession: (next: SessionSnapshot | ((prev: SessionSnapshot) => SessionSnapshot)) => void;
  setSessionDataMode: Dispatch<SetStateAction<"shared" | "independent">>;
  setSettingsFocusAnchor: Dispatch<SetStateAction<string | null>>;
  setSetup: Dispatch<SetStateAction<SetupFlags>>;
  setShowMessageTimestamps: Dispatch<SetStateAction<boolean>>;
  setShowProductTutorial: Dispatch<SetStateAction<boolean>>;
  setShowReplyLength: Dispatch<SetStateAction<boolean>>;
  setShowShortcuts: Dispatch<SetStateAction<boolean>>;
  setSidebarShowRelativeTime: Dispatch<SetStateAction<boolean>>;
  setSkillsReloadToken: Dispatch<SetStateAction<number>>;
  setStoreApiKeysInKeychain: Dispatch<SetStateAction<boolean>>;
  setStreamStallSeconds: Dispatch<SetStateAction<number>>;
  setSttCustomBaseUrl: Dispatch<SetStateAction<string>>;
  setSttCustomLanguage: Dispatch<SetStateAction<string>>;
  setSttCustomModel: Dispatch<SetStateAction<string>>;
  setSttEngine: Dispatch<SetStateAction<string>>;
  setSttZhScript: Dispatch<SetStateAction<string>>;
  setSubagentWorktreeSnapshotEnabled: Dispatch<SetStateAction<boolean>>;
  setSubagentsEnabled: Dispatch<SetStateAction<boolean>>;
  setToast: Dispatch<SetStateAction<string | null>>;
  setTodoGateEnabled: Dispatch<SetStateAction<boolean>>;
  setTodoGateMaxFiresPerPrompt: Dispatch<SetStateAction<number>>;
  setTrayBusyBadge: Dispatch<SetStateAction<boolean>>;
  setTwoPassCompactionEnabled: Dispatch<SetStateAction<boolean>>;
  setUseLeader: Dispatch<SetStateAction<boolean>>;
  setVoiceDictationAutoSend: Dispatch<SetStateAction<boolean>>;
  setVoiceId: Dispatch<SetStateAction<string>>;
  setVoiceKeepAgentsOnEnd: Dispatch<SetStateAction<boolean>>;
  setWinTaskbarOverlay: Dispatch<SetStateAction<boolean>>;
  setWindowAlwaysOnTop: Dispatch<SetStateAction<boolean>>;
  setWorkflowsEnabled: Dispatch<SetStateAction<boolean>>;
  setZenModeEnabled: (enabled: boolean) => void;
  settingsFocusAnchor: string | null;
  settingsLabels: Record<string, string>;
  settingsSection: SettingsSectionId;
  settingsTab: SettingsTabId | null;
  showMessageTimestamps: boolean;
  showReplyLength: boolean;
  showToast: (msg: string, ms?: number) => void;
  sidebarShowRelativeTime: boolean;
  skin: ThemeSkinId;
  storeApiKeysInKeychain: boolean;
  streamStallSeconds: number;
  sttCustomBaseUrl: string;
  sttCustomLanguage: string;
  sttCustomModel: string;
  sttEngine: string;
  sttZhScript: string;
  subagentWorktreeSnapshotEnabled: boolean;
  subagentsEnabled: boolean;
  submitAccountLoginCode: (code: string) => Promise<void>;
  theme: Theme;
  themePreference: ThemePreference;
  themeSchedule: ThemeScheduleConfig;
  todoGateEnabled: boolean;
  todoGateMaxFiresPerPrompt: number;
  tr: TFn;
  trayBusyBadge: boolean;
  trayHandlersRef: RefObject<TrayHandlers>;
  twoPassCompactionEnabled: boolean;
  unreadSessionIds: Set<string>;
  useLeader: boolean;
  voiceDictationAutoSend: boolean;
  voiceId: string;
  voiceKeepAgentsOnEnd: boolean;
  wallpaperRecord: WallpaperRecord | null;
  wallpaperScrim: number;
  wallpaperBlur: number;
  wallpaperUrl: string | null;
  winTaskbarOverlay: boolean;
  windowAlwaysOnTop: boolean;
  workflowsEnabled: boolean;
  zenMode: boolean;
};
