//! Flat Tauri command registry, grouped by domain.
//!
//! New commands belong inside the matching section. When none fits, add a
//! new `// ── Domain ──` section rather than appending at a random spot.

use crate::{
    cli_worktrees, commands, desktop_notify, git_pr_hub, leader, mirror, os_theme, pet_window,
    remote_im, serve, session_api, ssh_remote, system_fonts, theme_editor_window, tray, updater,
    voice_host, wallpaper_grok_album, wallpaper_remote_commands,
};

/// Single invoke handler consumed by `Builder::invoke_handler` in `run()`.
///
/// `generate_handler!` only accepts a flat list, so domain separation is
/// expressed with section comments instead of nested arrays.
pub fn app_invoke_handler(
) -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // ── Sessions, turns, permissions & local session API ──
        commands::session_get_state,
        commands::session_connect,
        commands::session_prewarm,
        commands::session_send,
        session_api::session_api_status,
        session_api::session_api_reveal_token_file,
        session_api::session_api_install_cli,
        session_api::session_api_remove_cli,
        session_api::session_api_reveal_cli_link,
        commands::session_interject,
        commands::session_stop,
        commands::session_disconnect,
        commands::session_reattach,
        commands::session_resolve_permission,
        commands::session_pending_permission,
        commands::session_pending_ask_user,
        commands::session_resolve_plan,
        commands::session_plan_chrome_get,
        commands::session_plan_chrome_set,
        commands::session_agent_plan_snapshot,
        commands::session_resolve_ask_user,
        // ── CLI & environment probe ──
        commands::probe_cli,
        commands::wsl_status,
        // ── SSH remote hosts ──
        ssh_remote::ssh_list_hosts,
        ssh_remote::ssh_test_host,
        ssh_remote::ssh_watch_start,
        ssh_remote::ssh_watch_stop,
        ssh_remote::ssh_list_dir,
        ssh_remote::ssh_read_file,
        ssh_remote::ssh_write_file,
        ssh_remote::ssh_list_sessions,
        ssh_remote::ssh_open_session,
        ssh_remote::ssh_delete_sessions,
        ssh_remote::ssh_browser_prepare,
        // ── CLI install/update, ACP probe & app update ──
        commands::cli_repair_agent_sidecar,
        commands::acp_test_connection,
        commands::acp_server_probe,
        commands::cli_install_latest,
        commands::cli_install_commands,
        commands::cli_update_check,
        commands::cli_update_install,
        commands::pick_cli_binary,
        commands::pick_agent_profile,
        commands::open_external_url,
        commands::app_check_update,
        updater::is_auto_update_supported,
        updater::is_updater_plugin_enabled,
        updater::updater_status,
        updater::prepare_for_app_update,
        // ── Voice (status & transcribe) ──
        commands::voice_status,
        commands::voice_transcribe,
        // ── Projects & workspaces ──
        commands::projects_list,
        commands::general_workspace_path,
        commands::project_add,
        commands::project_add_ssh,
        commands::project_add_dialog,
        commands::project_remove,
        commands::project_relocate,
        commands::project_trust,
        commands::project_set_permission_policy,
        commands::project_set_sandbox_profile,
        commands::project_rename,
        commands::project_set_pinned,
        commands::projects_reorder,
        commands::project_set_color,
        commands::project_reveal,
        commands::project_rules_list,
        commands::project_rules_invalidate_sessions,
        commands::project_rules_ensure_template,
        commands::project_archive_sessions,
        commands::workspaces_list,
        commands::workspaces_for_project,
        commands::workspace_get,
        commands::workspace_upsert,
        commands::workspace_delete,
        commands::workspace_validate_root,
        commands::workspaces_diagnose,
        commands::session_set_workspace,
        // ── Session list/search & CLI session import ──
        commands::sessions_list,
        commands::sessions_search,
        commands::cli_sessions_list,
        commands::cli_sessions_search,
        commands::cli_session_import,
        commands::cli_sessions_import_all,
        commands::cli_sessions_delete,
        commands::cli_session_find_latest_for_cwd,
        commands::cli_session_continue_cwd,
        // ── Session CRUD, media & session metadata ──
        commands::session_create,
        commands::open_session_window,
        theme_editor_window::open_theme_editor_window,
        commands::focus_main_window,
        commands::session_delete,
        commands::session_rename,
        commands::session_set_archived,
        commands::session_set_pinned,
        commands::session_set_worktree,
        commands::session_set_json_schema,
        commands::session_set_project,
        commands::session_move_to_project,
        commands::session_set_plugin_dirs,
        commands::session_set_extra_rules,
        commands::session_set_max_agent_turns,
        commands::session_set_system_prompt_override,
        commands::session_set_no_ask_user,
        commands::session_set_fork_agent_session,
        commands::session_set_scheduled,
        commands::session_messages,
        commands::session_interrupt_context,
        commands::session_media_root,
        commands::session_resolve_relative_media,
        commands::media_server_endpoint,
        commands::media_file_info,
        commands::media_read_file_chunk,
        // ── Settings, memory & agent config ──
        commands::settings_get,
        commands::store_take_quarantine,
        commands::settings_set,
        commands::memory_clear,
        commands::memory_list,
        commands::memory_delete_file,
        commands::agent_config_toml_read,
        commands::memory_search,
        commands::memory_embed_config_get,
        commands::memory_embed_config_set,
        commands::settings_remember_last_session,
        // ── Models, agents catalog & composer prefs ──
        commands::models_list_available,
        commands::agents_catalog,
        commands::composer_prefs_resolve,
        commands::composer_prefs_set,
        // ── Permission policy, privacy & codebase indexing ──
        commands::session_set_policy,
        commands::permission_rules_get,
        commands::permission_rules_set,
        commands::agent_config_edit_get,
        commands::agent_config_edit_set,
        commands::privacy_config_get,
        commands::privacy_config_set,
        commands::codebase_indexing_get,
        commands::codebase_indexing_set,
        // ── Session model, rewind & fork ──
        commands::session_set_model,
        commands::session_rewind_drop_last_user,
        commands::session_rewind_points,
        commands::session_rewind_execute,
        commands::session_fork,
        // ── Secrets & provider ping ──
        commands::secrets_get_masked,
        commands::secrets_set,
        commands::provider_ping,
        // ── Grok CLI / Go config import ──
        commands::import_grok_cli_config,
        commands::import_grok_go_config,
        // ── Doctor, diagnostics, audit ledger & export ──
        commands::doctor_report,
        commands::network_probe,
        commands::probe_streaming_acp_ndjson,
        commands::agents_recycle_all,
        commands::cli_doctor_fix,
        commands::export_support_bundle,
        commands::process_budget_snapshot,
        commands::audit_ledger_list,
        commands::audit_ledger_clear,
        commands::audit_ledger_prune,
        commands::audit_ledger_export,
        commands::export_session_bundle,
        commands::session_cli_export,
        commands::export_bytes_save,
        commands::session_trace_export,
        commands::reset_app_data,
        // ── Skills ──
        commands::skills_list,
        commands::skills_compat_set,
        commands::skill_read,
        commands::skill_write,
        commands::skill_roots,
        commands::skill_create,
        commands::customize_commands_list,
        commands::customize_command_create,
        // ── Agents & workflows ──
        commands::agents_list,
        commands::workflows_list,
        commands::workflows_run,
        commands::workflows_create,
        commands::agents_scaffold,
        // ── Inspect (MCP & project) ──
        commands::inspect_mcp,
        commands::project_inspect,
        // ── Extensions & MCP ──
        commands::extensions_get,
        commands::extensions_set_mcp,
        commands::extensions_set_skill,
        commands::extensions_enable_all_mcp,
        commands::extensions_enable_all_skills,
        commands::mcp_add,
        commands::mcp_oauth_start,
        commands::mcp_oauth_status,
        commands::mcp_remove,
        commands::mcp_doctor,
        // ── Plugins & plugin MCP auth ──
        commands::plugins_list,
        commands::plugin_enable,
        commands::plugin_disable,
        commands::plugin_uninstall,
        commands::plugin_details,
        commands::plugin_install,
        commands::plugin_update,
        commands::plugin_validate,
        commands::plugin_mcp_auth_status,
        commands::plugin_mcp_auth_save_tokens,
        commands::plugin_mcp_auth_oauth2,
        commands::plugin_mcp_auth_logout,
        // ── Hooks ──
        commands::hooks_list,
        commands::hooks_reveal,
        commands::hooks_open_dir,
        commands::hooks_ensure_dir,
        commands::hooks_try_run,
        // ── First-run & managed setup ──
        commands::setup_preview,
        commands::setup_install,
        commands::managed_setup_status,
        // ── Plugin marketplace ──
        commands::marketplace_list,
        commands::marketplace_available,
        commands::marketplace_plugin_meta_index,
        commands::marketplace_add,
        commands::marketplace_remove,
        commands::marketplace_update,
        // ── Leader (fleet control) ──
        leader::leader_status,
        leader::leader_list,
        leader::leader_info,
        leader::leader_start,
        leader::leader_stop,
        leader::leader_kill_all,
        // ── Local HTTP serve ──
        serve::serve_status,
        serve::serve_start,
        serve::serve_stop,
        serve::serve_tcp_probe,
        // ── File pickers, clipboard & media helpers ──
        commands::pick_directory,
        commands::pick_attach_files,
        commands::pick_attach_folder,
        commands::save_temp_attachment,
        commands::clipboard_paste_image,
        commands::clipboard_file_paths,
        commands::clipboard_write_image_path,
        commands::clipboard_write_image,
        commands::paths_classify,
        commands::path_open,
        commands::path_reveal,
        commands::media_video_poster,
        commands::media_video_poster_save,
        commands::media_image_thumb,
        // ── Git, worktrees & PR hub ──
        commands::git_file_diff,
        commands::git_status,
        commands::git_review_bundle,
        commands::git_worktrees_list,
        commands::git_branches_list,
        commands::git_switch_branch,
        commands::git_worktree_add,
        commands::git_worktree_remove,
        commands::git_worktree_gc,
        commands::git_worktree_compare,
        commands::git_push_branch,
        commands::gh_pr_create,
        git_pr_hub::git_pr_list,
        git_pr_hub::git_pr_view,
        git_pr_hub::git_pr_checks,
        git_pr_hub::git_pr_comments,
        cli_worktrees::cli_worktrees_list,
        cli_worktrees::cli_worktree_db_path,
        cli_worktrees::cli_worktree_db_stats,
        cli_worktrees::cli_worktree_db_rebuild,
        commands::git_show_file,
        commands::apply_file_patch,
        commands::git_checkout_file,
        commands::delete_project_file,
        // ── Filesystem browser & codebase search ──
        commands::fs_list_dir,
        commands::project_codebase_search,
        commands::fs_read_file,
        commands::fs_write_file,
        commands::fs_write_absolute,
        // ── Tray, OS theme, fonts & notifications ──
        tray::tray_refresh,
        tray::tray_set_busy_count,
        tray::tray_set_windows_overlay,
        os_theme::os_theme_current,
        system_fonts::list_system_font_families,
        desktop_notify::desktop_notify_show,
        desktop_notify::desktop_notify_available,
        // ── App lifecycle & misc fs helpers ──
        commands::app_force_quit,
        commands::app_cancel_pending_quit,
        commands::fs_read_absolute,
        commands::fs_open_path,
        commands::fs_resolve_path,
        commands::session_auto_title,
        // ── Automations & scheduler ──
        commands::automations_list,
        commands::automation_create,
        commands::automation_update,
        commands::automation_set_enabled,
        commands::automation_mark_run,
        commands::automation_delete,
        commands::automation_runner_status,
        commands::schedules_launch_agent_status,
        commands::schedules_launch_agent_set_enabled,
        commands::schedules_launch_agent_reveal_helper,
        // ── Accounts, quota & transcript import ──
        commands::account_status,
        commands::account_login,
        commands::account_login_cancel,
        commands::account_login_submit_code,
        commands::account_logout,
        commands::account_open_usage,
        commands::account_open_subscribe,
        commands::accounts_list,
        commands::accounts_quota,
        commands::account_save_current,
        commands::account_switch,
        commands::account_remove,
        commands::account_rename,
        commands::session_import_transcript,
        commands::session_import_transcript_file,
        // ── Providers, aux models & editors ──
        commands::providers_list,
        commands::providers_upsert,
        commands::providers_remove,
        commands::providers_set_default,
        commands::providers_activate,
        commands::providers_ping,
        commands::providers_list_models,
        commands::providers_test_model,
        commands::providers_balance,
        commands::providers_cc_switch_scan,
        commands::providers_cc_switch_import,
        commands::models_aux_get,
        commands::models_aux_set,
        commands::models_aux_apply_save_grok,
        commands::models_aux_reset_defaults,
        commands::models_aux_headless,
        commands::models_aux_web_search,
        commands::official_aux_status,
        commands::official_aux_ensure_home,
        commands::official_aux_dispatch,
        commands::official_aux_web_search,
        commands::official_aux_x_keyword_search,
        commands::official_aux_x_semantic_search,
        commands::official_aux_x_user_search,
        commands::official_aux_x_thread_fetch,
        commands::official_aux_vision_describe,
        commands::editors_list,
        commands::open_in_editor,
        // ── Mobile web mirror ──
        mirror::mirror_status,
        mirror::mirror_rotate_token,
        mirror::mirror_set_read_only,
        mirror::mirror_set_max_clients,
        mirror::mirror_set_allow_lan,
        mirror::mirror_start,
        mirror::mirror_stop,
        // ── Voice host ──
        voice_host::voice_state,
        voice_host::voice_start,
        voice_host::voice_stop,
        voice_host::voice_push_pcm,
        voice_host::voice_invoke_tool,
        voice_host::voice_dictation_transcribe,
        // ── Remote IM bridge ──
        remote_im::remote_im_bridge_status,
        remote_im::remote_im_bridge_start,
        remote_im::remote_im_bridge_stop,
        remote_im::remote_im_bridge_set_config,
        remote_im::remote_im_bridge_reload,
        remote_im::remote_im_test_connection,
        remote_im::remote_im_scan_begin,
        remote_im::remote_im_scan_poll,
        remote_im::remote_im_list_instances,
        remote_im::remote_im_save_instance,
        remote_im::remote_im_delete_instance,
        remote_im::remote_im_doctor,
        // ── Wallpaper: remote provider search & media ──
        wallpaper_remote_commands::wallpaper_remote_search,
        wallpaper_remote_commands::wallpaper_remote_search_more,
        wallpaper_remote_commands::wallpaper_remote_search_cancel,
        wallpaper_remote_commands::wallpaper_remote_fetch_media,
        wallpaper_remote_commands::wallpaper_remote_thumbnail,
        wallpaper_remote_commands::wallpaper_remote_cancel_media_requests,
        wallpaper_remote_commands::wallpaper_remote_cancel_all_media_requests,
        // ── Wallpaper: X search, imagine & library ──
        commands::wallpaper_x_search,
        commands::wallpaper_x_search_cancel,
        commands::wallpaper_x_search_more,
        commands::wallpaper_fetch_media,
        commands::wallpaper_imagine,
        commands::wallpaper_image_to_video,
        commands::wallpaper_image_to_video_cancel,
        commands::wallpaper_image_edit,
        commands::wallpaper_imagine_recover_catalog,
        commands::wallpaper_imagine_pending_recoveries,
        commands::wallpaper_import_image,
        commands::wallpaper_library_list,
        commands::wallpaper_library_page,
        commands::wallpaper_library_remember,
        commands::wallpaper_library_lookup,
        commands::wallpaper_library_find_by_id,
        commands::wallpaper_library_delete,
        // ── Wallpaper: Grok album ──
        wallpaper_grok_album::wallpaper_grok_album_open,
        wallpaper_grok_album::wallpaper_grok_album_snapshot,
        wallpaper_grok_album::wallpaper_grok_album_refresh,
        wallpaper_grok_album::wallpaper_grok_album_load_more,
        wallpaper_grok_album::wallpaper_grok_album_thumbnail,
        wallpaper_grok_album::wallpaper_grok_album_cancel_requests,
        wallpaper_grok_album::wallpaper_grok_album_cancel_all_requests,
        wallpaper_grok_album::wallpaper_grok_album_fetch_media,
        // ── Appearance skins ──
        commands::skin_pick_open,
        commands::skin_pick_save,
        commands::skin_pack_inspect,
        commands::skin_inspect_abort,
        commands::skin_pack_export,
        commands::skin_staging_begin,
        commands::skin_staging_append,
        commands::skin_staging_abort,
        commands::skin_preset_list,
        commands::skin_preset_save_from_upload,
        commands::skin_preset_save_from_inspect,
        commands::skin_preset_materialize,
        commands::skin_preset_delete,
        commands::skin_preset_rename,
        commands::skin_preset_replace_from_upload,
        commands::skin_preset_export,
        commands::skin_undo_prepare,
        commands::skin_undo_append,
        commands::skin_undo_commit,
        commands::skin_undo_abort,
        commands::skin_catalog_fetch,
        commands::skin_catalog_download,
        commands::skin_catalog_preview_path,
        commands::skin_sources_list,
        commands::skin_sources_add,
        commands::skin_sources_remove,
        commands::skin_sources_set_enabled,
        commands::skin_import_take_pending,
        commands::skin_pack_fetch_url,
        // ── Streaming probe, batch agents & X evidence ──
        commands::streaming_messages_json_probe,
        commands::batch_agents_headless,
        commands::x_evidence_search,
        commands::x_evidence_list,
        commands::x_evidence_get,
        commands::x_evidence_stats,
        commands::x_quote_pack,
        commands::path_exists_many,
        // ── Terminal PTY ──
        commands::terminal_pty_spawn,
        commands::terminal_pty_write,
        commands::terminal_pty_resize,
        commands::terminal_pty_kill,
        // ── Side browser ──
        commands::side_browser_create,
        commands::side_browser_close,
        commands::side_browser_list,
        commands::side_browser_navigate,
        commands::side_browser_reload,
        commands::side_browser_url,
        commands::side_browser_eval,
        commands::side_browser_snapshot,
        commands::side_browser_install_download_hook,
        // ── Computer Use: authorization, lifecycle & runtime ──
        commands::computer_use_status,
        commands::computer_use_helper_status,
        commands::computer_use_helper_action,
        commands::computer_use_set_feature,
        commands::computer_use_list_targets,
        commands::computer_use_authorize_surface,
        commands::computer_use_cancel_authorization,
        commands::computer_use_observe,
        commands::computer_use_pause,
        commands::computer_use_resume,
        commands::computer_use_takeover,
        commands::computer_use_stop,
        commands::computer_use_retry_cleanup,
        commands::computer_use_set_preview,
        commands::computer_use_runtime_status,
        commands::computer_use_runtime_repair,
        commands::computer_use_runtime_rollback,
        commands::computer_use_begin_pairing,
        commands::computer_use_confirm_pairing_app,
        commands::computer_use_revoke_pairing,
        commands::computer_use_list_shared_tabs,
        commands::computer_use_unbind_webview,
        commands::computer_use_export_bundle,
        commands::computer_use_clear_traces,
        commands::computer_use_clear_staging,
        commands::computer_use_clear_managed_profiles,
        // ── Desktop pet ──
        pet_window::pet_prefs_get,
        pet_window::pet_prefs_set,
        pet_window::pet_show,
        pet_window::pet_hide,
        pet_window::pet_toggle,
        pet_window::pet_is_visible,
        pet_window::pet_set_ignore_cursor,
        pet_window::pet_set_dragging,
        pet_window::pet_nudge,
        pet_window::pet_set_menu_open,
        pet_window::pet_webview_ready,
        pet_window::pet_overlay_policy,
        pet_window::pet_push_focus,
        pet_window::pet_get_focus,
        pet_window::pet_open_settings,
        pet_window::pet_focus_session,
        pet_window::pet_show_main,
        pet_window::pet_hide_main,
        pet_window::pet_push_tasks,
        pet_window::pet_get_tasks,
        pet_window::pet_set_hit_chrome,
    ]
}
