//! CLI sandbox.toml helpers for multi-root workspaces (#1194 MVP-1 / v1).
//!
//! Independent mode: App may write `agent-home/sandbox.toml` with a custom
//! profile that extends `workspace` and grants `read_write` for declared
//! write roots. Shared mode: never rewrite `~/.grok`; capability stays
//! `context_only` unless the user already maintains a covering profile.

use crate::paths::agent_home_dir;
use crate::workspace_store::{
    WorkspaceCapability, WorkspaceRecord, WorkspaceRootAccess, WorkspaceRootRole,
};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;

pub const APP_PROFILE_PREFIX: &str = "app_ws_";

#[derive(Debug, Clone)]
#[allow(dead_code)] // surfaced to Doctor / UI later
pub struct WorkspaceSandboxPlan {
    pub profile_name: String,
    pub capability: WorkspaceCapability,
    pub profile_ref: Option<String>,
    pub reason: String,
    /// When set, spawn should pass `--sandbox <profile_name>` instead of the
    /// normal effective built-in profile.
    pub spawn_sandbox: Option<String>,
}

fn session_data_mode_is_independent(mode: &str) -> bool {
    mode.trim().eq_ignore_ascii_case("independent")
}

fn write_roots(ws: &WorkspaceRecord) -> Vec<String> {
    ws.roots
        .iter()
        .filter(|r| r.access == WorkspaceRootAccess::Write)
        .map(|r| r.path.clone())
        .collect()
}

fn extra_write_roots(ws: &WorkspaceRecord) -> Vec<String> {
    ws.roots
        .iter()
        .filter(|r| r.role == WorkspaceRootRole::Extra && r.access == WorkspaceRootAccess::Write)
        .map(|r| r.path.clone())
        .collect()
}

pub fn profile_name_for(ws: &WorkspaceRecord) -> String {
    let mut hasher = Sha256::new();
    hasher.update(ws.id.as_bytes());
    for r in &ws.roots {
        hasher.update(r.path.as_bytes());
        hasher.update(match r.access {
            WorkspaceRootAccess::Read => b"r",
            WorkspaceRootAccess::Write => b"w",
        });
    }
    let digest = hasher.finalize();
    let short = digest
        .iter()
        .take(4)
        .map(|b| format!("{b:02x}"))
        .collect::<String>();
    format!("{APP_PROFILE_PREFIX}{short}")
}

/// Render a custom sandbox.toml fragment for this workspace.
pub fn render_profile_toml(profile_name: &str, write_paths: &[String]) -> String {
    let mut out =
        String::from("# Generated by Grok App multi-root workspace — do not hand-edit.\n");
    out.push_str(&format!("[profiles.{profile_name}]\n"));
    out.push_str("extends = \"workspace\"\n");
    out.push_str("restrict_network = false\n");
    if !write_paths.is_empty() {
        out.push_str("read_write = [\n");
        for p in write_paths {
            let esc = p.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("  \"{esc}\",\n"));
        }
        out.push_str("]\n");
    }
    out
}

fn agent_home_sandbox_toml() -> PathBuf {
    agent_home_dir().join("sandbox.toml")
}

fn shared_sandbox_toml() -> PathBuf {
    crate::process_util::user_home()
        .join(".grok")
        .join("sandbox.toml")
}

/// Probe OS-level writability (not CLI kernel sandbox). Creates and removes a
/// probe file under each write root.
pub fn smoke_os_write_roots(paths: &[String]) -> Result<(), String> {
    for raw in paths {
        let dir = Path::new(raw);
        if !dir.is_dir() {
            return Err(format!("write root missing: {raw}"));
        }
        // Unique name so we never clobber a user file named `.grok-app-ws-probe`.
        let probe = dir.join(format!(".grok-app-ws-probe-{}", Uuid::new_v4().simple()));
        fs::write(&probe, b"ok").map_err(|e| format!("write probe failed in {raw}: {e}"))?;
        fs::remove_file(&probe).map_err(|e| format!("cleanup probe failed in {raw}: {e}"))?;
    }
    Ok(())
}

/// Ensure independent agent-home has a profile covering write roots.
pub fn ensure_independent_profile(ws: &WorkspaceRecord) -> Result<WorkspaceSandboxPlan, String> {
    let extras = extra_write_roots(ws);
    if extras.is_empty() {
        return Ok(WorkspaceSandboxPlan {
            profile_name: String::new(),
            capability: WorkspaceCapability::ContextOnly,
            profile_ref: None,
            reason: "no extra write roots".into(),
            spawn_sandbox: None,
        });
    }
    let writes = write_roots(ws);
    smoke_os_write_roots(&writes)?;
    let name = profile_name_for(ws);
    let body = render_profile_toml(&name, &writes);
    let path = agent_home_sandbox_toml();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    // Merge: replace our generated section if present, else append.
    let existing = fs::read_to_string(&path).unwrap_or_default();
    let merged = merge_or_replace_profile(&existing, &name, &body);
    fs::write(&path, merged).map_err(|e| format!("write sandbox.toml: {e}"))?;
    Ok(WorkspaceSandboxPlan {
        profile_name: name.clone(),
        capability: WorkspaceCapability::ExtraWriteActive,
        profile_ref: Some(format!("app_managed:{name}")),
        reason: "independent app-managed profile written".into(),
        spawn_sandbox: Some(name),
    })
}

fn merge_or_replace_profile(existing: &str, profile_name: &str, body: &str) -> String {
    let marker = format!("[profiles.{profile_name}]");
    if !existing.contains(&marker) {
        let mut out = existing.trim_end().to_string();
        if !out.is_empty() {
            out.push_str("\n\n");
        }
        out.push_str(body);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        return out;
    }
    // Drop previous section for this profile name (until next [profiles. or EOF).
    let mut out = String::new();
    let mut skipping = false;
    for line in existing.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("[profiles.") {
            if trimmed == marker.as_str() || trimmed.starts_with(marker.as_str()) {
                skipping = true;
                continue;
            }
            skipping = false;
        }
        if skipping {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    if !out.is_empty() && !out.ends_with("\n\n") {
        out.push('\n');
    }
    out.push_str(body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Shared mode: never write ~/.grok. Detect a user profile that already lists
/// every write root under some `read_write` array (best-effort text scan).
pub fn detect_shared_capability(ws: &WorkspaceRecord) -> WorkspaceSandboxPlan {
    let extras = extra_write_roots(ws);
    if extras.is_empty() {
        return WorkspaceSandboxPlan {
            profile_name: String::new(),
            capability: WorkspaceCapability::ContextOnly,
            profile_ref: None,
            reason: "no extra write roots".into(),
            spawn_sandbox: None,
        };
    }
    let path = shared_sandbox_toml();
    let Ok(text) = fs::read_to_string(&path) else {
        return WorkspaceSandboxPlan {
            profile_name: String::new(),
            capability: WorkspaceCapability::ContextOnly,
            profile_ref: Some("user_managed:missing".into()),
            reason: "shared mode: no ~/.grok/sandbox.toml — cross-root write disabled".into(),
            spawn_sandbox: None,
        };
    };
    let writes = write_roots(ws);
    if let Some(profile) = find_covering_profile(&text, &writes) {
        WorkspaceSandboxPlan {
            profile_name: profile.clone(),
            capability: WorkspaceCapability::ExtraWriteActive,
            profile_ref: Some(format!("user_managed:{profile}")),
            reason: "shared mode: a user profile read_write covers all write roots".into(),
            spawn_sandbox: Some(profile),
        }
    } else {
        WorkspaceSandboxPlan {
            profile_name: String::new(),
            capability: WorkspaceCapability::ContextOnly,
            profile_ref: Some("user_managed:incomplete".into()),
            reason: "shared mode: no single user profile lists all write roots".into(),
            spawn_sandbox: None,
        }
    }
}

/// Pick a `[profiles.X]` whose own `read_write` list contains every path.
fn find_covering_profile(text: &str, write_paths: &[String]) -> Option<String> {
    if write_paths.is_empty() {
        return None;
    }
    let mut current: Option<String> = None;
    let mut rw_block = false;
    let mut covered: Vec<String> = Vec::new();
    let mut best: Option<String> = None;

    let flush = |name: &Option<String>, covered: &mut Vec<String>, best: &mut Option<String>| {
        if let Some(n) = name {
            if write_paths.iter().all(|p| covered.iter().any(|c| c == p)) {
                *best = Some(n.clone());
            }
        }
        covered.clear();
    };

    for line in text.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("[profiles.") {
            flush(&current, &mut covered, &mut best);
            if best.is_some() {
                break;
            }
            current = rest.strip_suffix(']').map(|s| s.trim().to_string());
            rw_block = false;
            continue;
        }
        if trimmed.starts_with('[') {
            flush(&current, &mut covered, &mut best);
            if best.is_some() {
                break;
            }
            current = None;
            rw_block = false;
            continue;
        }
        if trimmed.starts_with("read_write") {
            rw_block = true;
        } else if trimmed.starts_with("read_only")
            || trimmed.starts_with("deny")
            || trimmed.starts_with("extends")
            || trimmed.starts_with("restrict_network")
        {
            rw_block = trimmed.starts_with("read_write");
        }
        if !rw_block {
            continue;
        }
        for p in write_paths {
            if trimmed.contains(p) && !covered.iter().any(|c| c == p) {
                covered.push(p.clone());
            }
        }
        if trimmed.contains(']') {
            rw_block = false;
        }
    }
    flush(&current, &mut covered, &mut best);
    best
}

pub fn plan_for_session_mode(
    session_data_mode: &str,
    ws: &WorkspaceRecord,
) -> Result<WorkspaceSandboxPlan, String> {
    if session_data_mode_is_independent(session_data_mode) {
        ensure_independent_profile(ws)
    } else {
        Ok(detect_shared_capability(ws))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::workspace_store::{WorkspaceRoot, WorkspaceRootAccess, WorkspaceRootRole};
    use chrono::Utc;

    fn sample_ws(extra_write: bool) -> WorkspaceRecord {
        WorkspaceRecord {
            id: "ws_test".into(),
            name: "t".into(),
            primary_project_id: "p1".into(),
            roots: vec![
                WorkspaceRoot {
                    path: "/tmp/a".into(),
                    role: WorkspaceRootRole::Primary,
                    access: WorkspaceRootAccess::Write,
                    path_ok: Some(true),
                },
                WorkspaceRoot {
                    path: "/tmp/b".into(),
                    role: WorkspaceRootRole::Extra,
                    access: if extra_write {
                        WorkspaceRootAccess::Write
                    } else {
                        WorkspaceRootAccess::Read
                    },
                    path_ok: Some(true),
                },
            ],
            profile_ref: None,
            capability: WorkspaceCapability::ContextOnly,
            capability_reason: None,
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn render_includes_read_write_paths() {
        let toml = render_profile_toml("app_ws_deadbeef", &["/tmp/a".into(), "/tmp/b".into()]);
        assert!(toml.contains("[profiles.app_ws_deadbeef]"));
        assert!(toml.contains("extends = \"workspace\""));
        assert!(toml.contains("\"/tmp/a\""));
        assert!(toml.contains("\"/tmp/b\""));
    }

    #[test]
    fn profile_name_stable_for_same_roots() {
        let a = profile_name_for(&sample_ws(true));
        let b = profile_name_for(&sample_ws(true));
        assert_eq!(a, b);
        assert!(a.starts_with(APP_PROFILE_PREFIX));
    }

    #[test]
    fn find_covering_profile_picks_matching_section() {
        let toml = r#"
[profiles.alpha]
extends = "workspace"
read_write = ["/tmp/other"]

[profiles.beta]
extends = "workspace"
read_write = ["/tmp/a", "/tmp/b"]
"#;
        let got = find_covering_profile(toml, &["/tmp/a".into(), "/tmp/b".into()]);
        assert_eq!(got.as_deref(), Some("beta"));
        assert!(find_covering_profile(toml, &["/tmp/missing".into()]).is_none());
    }

    #[test]
    fn merge_replaces_existing_section() {
        let old = "[profiles.app_ws_aaaa]\nextends = \"workspace\"\nread_write = [\"/old\"]\n\n[profiles.other]\nextends = \"strict\"\n";
        let body = render_profile_toml("app_ws_aaaa", &["/new".into()]);
        let merged = merge_or_replace_profile(old, "app_ws_aaaa", &body);
        assert!(merged.contains("\"/new\""));
        assert!(!merged.contains("\"/old\""));
        assert!(merged.contains("[profiles.other]"));
    }
}
